copy "Patches\%1\corlib-System.Reflection-MemberInfo.Partial.cs" build\class\corlib\System.Reflection\MemberInfo.Partial.cs
copy "Patches\%1\corlib-Mono.Security.Cryptography-KeyPairPersistence.Partial.cs" build\class\corlib\Mono.Security.Cryptography\KeyPairPersistence.Partial.cs
copy "Patches\%1\corlib-System-Environment.Partial.cs" build\class\corlib\System\Environment.Partial.cs
copy "Patches\%1\corlib-System.Threading-WaitHandle.Partial.cs" build\class\corlib\System.Threading\WaitHandle.Partial.cs
copy "Patches\%1\corlib-Decimal.Partial.cs" build\class\corlib\System\Decimal.Partial.cs 
copy "Patches\%1\corlib-System.Threading-Interlocked.Partial.cs" build\class\corlib\System.Threading\Interlocked.Partial.cs 
copy "Patches\%1\corlib-Array.Partial.cs" build\class\corlib\System\Array.Partial.cs
copy "Patches\%1\System-System.Configuration-ConfigurationSettings.Partial.cs" build\class\System\System.Configuration\ConfigurationSettings.Partial.cs
copy "Patches\%1\corlib-System.IO.IsolatedStorage-MoonIsolatedStorage.Partial.cs" build\class\corlib\System.IO.IsolatedStorage\MoonIsolatedStorage.Partial.cs
copy "Patches\%1\corlib-System.IO.IsolatedStorage-MoonIsolatedStorageFile.Partial.cs" build\class\corlib\System.IO.IsolatedStorage\MoonIsolatedStorageFile.Partial.cs
