// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using System.Collections.Generic;

namespace Mosa.Platform.ARMv6
{
	/// <summary>
	/// ARMv6 Instruction Map
	/// </summary>
	public static class ARMv6InstructionMap
	{
		public static readonly Dictionary<string, ARMv6Instruction> Map = new Dictionary<string, ARMv6Instruction>() {
			{ "Adc32", ARMv6.Adc32 },
			{ "Add32", ARMv6.Add32 },
			{ "Adr32", ARMv6.Adr32 },
			{ "And32", ARMv6.And32 },
			{ "Asr32", ARMv6.Asr32 },
			{ "B32", ARMv6.B32 },
			{ "Bic32", ARMv6.Bic32 },
			{ "Bkpt32", ARMv6.Bkpt32 },
			{ "Bl32", ARMv6.Bl32 },
			{ "Blx32", ARMv6.Blx32 },
			{ "Bx32", ARMv6.Bx32 },
			{ "Cmn32", ARMv6.Cmn32 },
			{ "Cmp32", ARMv6.Cmp32 },
			{ "Dmb32", ARMv6.Dmb32 },
			{ "Dsb32", ARMv6.Dsb32 },
			{ "Eor32", ARMv6.Eor32 },
			{ "Isb32", ARMv6.Isb32 },
			{ "Ldm32", ARMv6.Ldm32 },
			{ "Ldmfd32", ARMv6.Ldmfd32 },
			{ "Ldmia32", ARMv6.Ldmia32 },
			{ "Ldr32", ARMv6.Ldr32 },
			{ "Ldrb32", ARMv6.Ldrb32 },
			{ "Ldrh32", ARMv6.Ldrh32 },
			{ "Ldrsb32", ARMv6.Ldrsb32 },
			{ "Ldrsh32", ARMv6.Ldrsh32 },
			{ "Lsl32", ARMv6.Lsl32 },
			{ "Lsr32", ARMv6.Lsr32 },
			{ "Mov32", ARMv6.Mov32 },
			{ "Mrs32", ARMv6.Mrs32 },
			{ "Msr32", ARMv6.Msr32 },
			{ "Mul32", ARMv6.Mul32 },
			{ "Mvn32", ARMv6.Mvn32 },
			{ "Nop32", ARMv6.Nop32 },
			{ "Orr32", ARMv6.Orr32 },
			{ "Pop32", ARMv6.Pop32 },
			{ "Push32", ARMv6.Push32 },
			{ "Rev32", ARMv6.Rev32 },
			{ "Rev16", ARMv6.Rev16 },
			{ "Revsh32", ARMv6.Revsh32 },
			{ "Ror32", ARMv6.Ror32 },
			{ "Rsb32", ARMv6.Rsb32 },
			{ "Rsc32", ARMv6.Rsc32 },
			{ "Sbc32", ARMv6.Sbc32 },
			{ "Sev32", ARMv6.Sev32 },
			{ "Stm32", ARMv6.Stm32 },
			{ "Stmea32", ARMv6.Stmea32 },
			{ "Stmia32", ARMv6.Stmia32 },
			{ "Str32", ARMv6.Str32 },
			{ "Strb32", ARMv6.Strb32 },
			{ "Strh32", ARMv6.Strh32 },
			{ "Sub32", ARMv6.Sub32 },
			{ "Svc32", ARMv6.Svc32 },
			{ "Swi32", ARMv6.Swi32 },
			{ "Sxtb32", ARMv6.Sxtb32 },
			{ "Sxth32", ARMv6.Sxth32 },
			{ "Teq32", ARMv6.Teq32 },
			{ "Tst32", ARMv6.Tst32 },
			{ "Uxtb32", ARMv6.Uxtb32 },
			{ "Uxth32", ARMv6.Uxth32 },
			{ "Wfe32", ARMv6.Wfe32 },
			{ "Wfi32", ARMv6.Wfi32 },
			{ "Yield32", ARMv6.Yield32 },
		};
	}
}
