#!/bin/bash

rdir=$(dirname $0)

if [ ! -f $rdir/bin/Mosa.Tool.Mosactl.exe ]; then
  $rdir/Tools/nuget/nuget.exe restore Source/Mosa.Tool.Mosactl.sln
  msbuild $rdir/Source/Mosa.Tool.Mosactl.sln
fi

mono $rdir/bin/Mosa.Tool.Mosactl.exe "$@"
