// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Transforms.Optimizations.Auto.Simplification;

/// <summary>
/// Xor32Max
/// </summary>
[Transform("IR.Optimizations.Auto.Simplification")]
public sealed class Xor32Max : BaseTransform
{
	public Xor32Max() : base(IR.Xor32, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override bool Match(Context context, Transform transform)
	{
		if (!context.Operand2.IsResolvedConstant)
			return false;

		if (context.Operand2.ConstantUnsigned64 != 0xFFFFFFFF)
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;

		var t1 = context.Operand1;

		context.SetInstruction(IR.Not32, result, t1);
	}
}

/// <summary>
/// Xor32Max_v1
/// </summary>
[Transform("IR.Optimizations.Auto.Simplification")]
public sealed class Xor32Max_v1 : BaseTransform
{
	public Xor32Max_v1() : base(IR.Xor32, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override bool Match(Context context, Transform transform)
	{
		if (!context.Operand1.IsResolvedConstant)
			return false;

		if (context.Operand1.ConstantUnsigned64 != 0xFFFFFFFF)
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;

		var t1 = context.Operand2;

		context.SetInstruction(IR.Not32, result, t1);
	}
}
