// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// AddCarryIn64
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class AddCarryIn64 : BaseIRInstruction
	{
		public AddCarryIn64()
			: base(3, 1)
		{
		}
	}
}
