// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// AddWithCarry64
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class AddWithCarry64 : BaseIRInstruction
	{
		public AddWithCarry64()
			: base(3, 1)
		{
		}
	}
}
