// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// BitCopyInt32ToFloatR4
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class BitCopyInt32ToFloatR4 : BaseIRInstruction
	{
		public override int ID { get { return 193; } }

		public BitCopyInt32ToFloatR4()
			: base(1, 1)
		{
		}
	}
}
