// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR;

/// <summary>
/// CheckedConversionR4ToI16
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
public sealed class CheckedConversionR4ToI16 : BaseIRInstruction
{
	public CheckedConversionR4ToI16()
		: base(1, 1)
	{
	}
}
