// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR;

/// <summary>
/// CheckThrowOverflow
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
public sealed class CheckThrowOverflow : BaseIRInstruction
{
	public CheckThrowOverflow()
		: base(1, 0)
	{
	}
}
