// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// ConvertFloatR4ToFloatR8
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class ConvertFloatR4ToFloatR8 : BaseIRInstruction
	{
		public override int ID { get { return 29; } }

		public ConvertFloatR4ToFloatR8()
			: base(1, 1)
		{
		}
	}
}
