// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// ConvertInteger64ToFloatR4
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class ConvertInteger64ToFloatR4 : BaseIRInstruction
	{
		public ConvertInteger64ToFloatR4()
			: base(1, 1)
		{
		}
	}
}

