// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// FilterEnd
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class FilterEnd : BaseIRInstruction
	{
		public FilterEnd()
			: base(0, 0)
		{
		}
	}
}
