// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.MosaTypeSystem;

namespace Mosa.Compiler.Framework.IR;

/// <summary>
/// GetHigh32
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
public sealed class GetHigh32 : BaseIRInstruction
{
	public GetHigh32()
		: base(1, 1)
	{
	}

	public override BuiltInType ResultType => BuiltInType.UInt32;

	public override BuiltInType ResultType2 => BuiltInType.UInt32;
}
