// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR;

/// <summary>
/// KillAll
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
public sealed class KillAll : BaseIRInstruction
{
	public KillAll()
		: base(0, 0)
	{
	}

	public override bool IgnoreDuringCodeGeneration => true;

	public override bool HasVariableOperands => true;
}
