// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// LoadObject
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class LoadObject : BaseIRInstruction
	{
		public LoadObject()
			: base(2, 1)
		{
		}

		public override bool IsMemoryRead { get { return true; } }
	}
}
