// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// RemUnsigned32
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class RemUnsigned32 : BaseIRInstruction
	{
		public RemUnsigned32()
			: base(2, 1)
		{
		}
	}
}
