// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// SubCarryOut32
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class SubCarryOut32 : BaseIRInstruction
	{
		public override int ID { get { return 161; } }

		public SubCarryOut32()
			: base(2, 2)
		{
		}
	}
}
