// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// SubWithCarry64
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class SubWithCarry64 : BaseIRInstruction
	{
		public override int ID { get { return 167; } }

		public SubWithCarry64()
			: base(3, 1)
		{
		}
	}
}
