// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.IR
{
	/// <summary>
	/// ZeroExtended8x32
	/// </summary>
	/// <seealso cref="Mosa.Compiler.Framework.IR.BaseIRInstruction" />
	public sealed class ZeroExtended8x32 : BaseIRInstruction
	{
		public ZeroExtended8x32()
			: base(1, 1)
		{
		}
	}
}

