// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Platform.x64.Instructions;

/// <summary>
/// Blsr32
/// </summary>
/// <seealso cref="Mosa.Platform.x64.X64Instruction" />
public sealed class Blsr32 : X64Instruction
{
	internal Blsr32()
		: base(1, 1)
	{
	}

	public override bool IsCommutative { get { return true; } }

	public override bool IsZeroFlagModified { get { return true; } }

	public override bool IsCarryFlagModified { get { return true; } }

	public override bool IsSignFlagModified { get { return true; } }

	public override bool IsOverflowFlagCleared { get { return true; } }

	public override bool IsOverflowFlagModified { get { return true; } }

	public override bool IsParityFlagUnchanged { get { return true; } }

	public override bool IsParityFlagUndefined { get { return true; } }

	public override void Emit(InstructionNode node, OpcodeEncoder opcodeEncoder)
	{
		System.Diagnostics.Debug.Assert(node.ResultCount == 1);
		System.Diagnostics.Debug.Assert(node.OperandCount == 1);

	}
}
