#!/bin/bash

NAME=mosa-debian-integration
IMAGE=seblon/mosa-debian-integration

#docker build . -t mosa/$NAME

docker rm -f $NAME

docker run -it --name $NAME -v ${PWD}/start:/home/mosa/start $IMAGE /bin/bash -c /home/mosa/start


