namespace System.Data.OleDb;

public enum OleDbLiteral
{
	Invalid,
	Binary_Literal,
	Catalog_Name,
	Catalog_Separator,
	Char_Literal,
	Column_Alias,
	Column_Name,
	Correlation_Name,
	Cursor_Name,
	Escape_Percent_Prefix,
	Escape_Underscore_Prefix,
	Index_Name,
	Like_Percent,
	Like_Underscore,
	Procedure_Name,
	Quote_Prefix,
	Schema_Name,
	Table_Name,
	Text_Command,
	User_Name,
	View_Name,
	Cube_Name,
	Dimension_Name,
	Hierarchy_Name,
	Level_Name,
	Member_Name,
	Property_Name,
	Schema_Separator,
	Quote_Suffix,
	Escape_Percent_Suffix,
	Escape_Underscore_Suffix
}
