// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Compiler.x86.Transforms.Optimizations.Auto.Lea;

[Transform()]
public sealed class Lea32RemoveScale : BaseTransform
{
	public Lea32RemoveScale() : base(X86.Lea32, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override bool Match(Context context, Transform transform)
	{
		if (!context.Operand2.IsConstantZero)
			return false;

		if (IsOne(context.Operand3))
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;

		var t1 = context.Operand1;
		var t2 = context.Operand4;

		var e1 = Operand.Constant32_0;
		var e2 = Operand.Constant32_1;

		context.SetInstruction(X86.Lea32, result, t1, e1, e2, t2);
	}
}
