namespace System.Reflection.Metadata;

public enum HandleKind : byte
{
	ModuleDefinition = 0,
	TypeReference = 1,
	TypeDefinition = 2,
	FieldDefinition = 4,
	MethodDefinition = 6,
	Parameter = 8,
	InterfaceImplementation = 9,
	MemberReference = 10,
	Constant = 11,
	CustomAttribute = 12,
	DeclarativeSecurityAttribute = 14,
	StandaloneSignature = 17,
	EventDefinition = 20,
	PropertyDefinition = 23,
	MethodImplementation = 25,
	ModuleReference = 26,
	TypeSpecification = 27,
	AssemblyDefinition = 32,
	AssemblyReference = 35,
	AssemblyFile = 38,
	ExportedType = 39,
	ManifestResource = 40,
	GenericParameter = 42,
	MethodSpecification = 43,
	GenericParameterConstraint = 44,
	Document = 48,
	MethodDebugInformation = 49,
	LocalScope = 50,
	LocalVariable = 51,
	LocalConstant = 52,
	ImportScope = 53,
	CustomDebugInformation = 55,
	UserString = 112,
	Blob = 113,
	Guid = 114,
	String = 120,
	NamespaceDefinition = 124
}
