// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Transforms.Optimizations.Auto.BitValue;

[Transform()]
public sealed class AddCarryOut64ButNotSigned : BaseTransform
{
	public AddCarryOut64ButNotSigned() : base(IR.AddCarryOut64, TransformType.Auto | TransformType.Optimization, true)
	{
	}

	public override int Priority => 20;

	public override bool Match(Context context, Transform transform)
	{
		if (!IsBitValueSignBitCleared64(context.Operand1))
			return false;

		if (!IsBitValueSignBitCleared64(context.Operand2))
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;
		var result2 = context.Result2;

		var t1 = context.Operand1;
		var t2 = context.Operand2;

		var e1 = Operand.CreateConstant(To32(0));

		context.SetInstruction(IR.Add64, result, t1, t2);
		context.AppendInstruction(IR.Move32, result2, e1);
	}
}
