// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Transforms.Optimizations.Auto.StrengthReduction;

/// <summary>
/// Or64And64ClearAndSet
/// </summary>
[Transform("IR.Optimizations.Auto.StrengthReduction")]
public sealed class Or64And64ClearAndSet : BaseTransform
{
	public Or64And64ClearAndSet() : base(IR.Or64, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override int Priority => 80;

	public override bool Match(Context context, Transform transform)
	{
		if (!context.Operand1.IsVirtualRegister)
			return false;

		if (!context.Operand1.IsDefinedOnce)
			return false;

		if (context.Operand1.Definitions[0].Instruction != IR.And64)
			return false;

		if (!IsResolvedConstant(context.Operand2))
			return false;

		if (!IsResolvedConstant(context.Operand1.Definitions[0].Operand2))
			return false;

		if (!IsZero(Not64(Or64(To64(context.Operand1.Definitions[0].Operand2), To64(context.Operand2)))))
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;

		var t1 = context.Operand1.Definitions[0].Operand1;
		var t2 = context.Operand2;

		context.SetInstruction(IR.Or64, result, t1, t2);
	}
}

/// <summary>
/// Or64And64ClearAndSet_v1
/// </summary>
[Transform("IR.Optimizations.Auto.StrengthReduction")]
public sealed class Or64And64ClearAndSet_v1 : BaseTransform
{
	public Or64And64ClearAndSet_v1() : base(IR.Or64, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override int Priority => 80;

	public override bool Match(Context context, Transform transform)
	{
		if (!context.Operand2.IsVirtualRegister)
			return false;

		if (!context.Operand2.IsDefinedOnce)
			return false;

		if (context.Operand2.Definitions[0].Instruction != IR.And64)
			return false;

		if (!IsResolvedConstant(context.Operand1))
			return false;

		if (!IsResolvedConstant(context.Operand2.Definitions[0].Operand2))
			return false;

		if (!IsZero(Not64(Or64(To64(context.Operand2.Definitions[0].Operand2), To64(context.Operand1)))))
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;

		var t1 = context.Operand1;
		var t2 = context.Operand2.Definitions[0].Operand1;

		context.SetInstruction(IR.Or64, result, t2, t1);
	}
}

/// <summary>
/// Or64And64ClearAndSet_v2
/// </summary>
[Transform("IR.Optimizations.Auto.StrengthReduction")]
public sealed class Or64And64ClearAndSet_v2 : BaseTransform
{
	public Or64And64ClearAndSet_v2() : base(IR.Or64, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override int Priority => 80;

	public override bool Match(Context context, Transform transform)
	{
		if (!context.Operand1.IsVirtualRegister)
			return false;

		if (!context.Operand1.IsDefinedOnce)
			return false;

		if (context.Operand1.Definitions[0].Instruction != IR.And64)
			return false;

		if (!IsResolvedConstant(context.Operand2))
			return false;

		if (!IsResolvedConstant(context.Operand1.Definitions[0].Operand1))
			return false;

		if (!IsZero(Not64(Or64(To64(context.Operand1.Definitions[0].Operand1), To64(context.Operand2)))))
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;

		var t1 = context.Operand1.Definitions[0].Operand2;
		var t2 = context.Operand2;

		context.SetInstruction(IR.Or64, result, t1, t2);
	}
}

/// <summary>
/// Or64And64ClearAndSet_v3
/// </summary>
[Transform("IR.Optimizations.Auto.StrengthReduction")]
public sealed class Or64And64ClearAndSet_v3 : BaseTransform
{
	public Or64And64ClearAndSet_v3() : base(IR.Or64, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override int Priority => 80;

	public override bool Match(Context context, Transform transform)
	{
		if (!context.Operand2.IsVirtualRegister)
			return false;

		if (!context.Operand2.IsDefinedOnce)
			return false;

		if (context.Operand2.Definitions[0].Instruction != IR.And64)
			return false;

		if (!IsResolvedConstant(context.Operand1))
			return false;

		if (!IsResolvedConstant(context.Operand2.Definitions[0].Operand1))
			return false;

		if (!IsZero(Not64(Or64(To64(context.Operand2.Definitions[0].Operand1), To64(context.Operand1)))))
			return false;

		return true;
	}

	public override void Transform(Context context, Transform transform)
	{
		var result = context.Result;

		var t1 = context.Operand1;
		var t2 = context.Operand2.Definitions[0].Operand2;

		context.SetInstruction(IR.Or64, result, t2, t1);
	}
}
