// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Transforms.Optimizations.Auto.StrengthReduction;

/// <summary>
/// SubManagedPointerSame
/// </summary>
[Transform("IR.Optimizations.Auto.StrengthReduction")]
public sealed class SubManagedPointerSame : BaseTransform
{
	public SubManagedPointerSame() : base(IRInstruction.SubManagedPointer, TransformType.Auto | TransformType.Optimization)
	{
	}

	public override int Priority => 80;

	public override bool Match(Context context, TransformContext transform)
	{
		if (!AreSame(context.Operand1, context.Operand2))
			return false;

		return true;
	}

	public override void Transform(Context context, TransformContext transform)
	{
		var result = context.Result;

		var e1 = Operand.CreateConstant(To32(0));

		context.SetInstruction(IRInstruction.MoveManagedPointer, result, e1);
	}
}
