/*
* (c) 2009 MOSA - The Managed Operating System Alliance
*
* Licensed under the terms of the New BSD License.
*
* Authors:
*  Phil Garcia (tgiphil) <phil@thinkedge.com>
*/

namespace Mosa.DeviceSystem.PCI
{
	/// <summary>
	/// 
	/// </summary>
	public static class DeviceTable
	{
		/// <summary>
		/// Lookups the specified vendor ID.
		/// </summary>
		/// <param name="vendorID">The vendor ID.</param>
		/// <returns></returns>
		public static string Lookup(ushort vendorID)
		{
			switch (vendorID)
			{
				case 0x0000: return "Gammagraphx, Inc. (or missing ID)";
				case 0x0010: return "Allied Telesyn International";
				case 0x001A: return "Ascend Communications, Inc.";
				case 0x001C: return "PEAK-System Technik GmbH";
				case 0x0033: return "Paradyne corp.";
				case 0x003D: return "Lockheed Martin-Marietta Corp";
				case 0x0059: return "Tiger Jet Network Inc. (Wrong ID)";
				case 0x0070: return "Hauppauge computer works Inc.";
				case 0x0071: return "Nebula Electronics Ltd.";
				case 0x0095: return "Silicon Image, Inc. (Wrong ID)";
				case 0x00A7: return "Teles AG (Wrong ID)";
				case 0x00F5: return "BFG Technologies, Inc.";
				case 0x0100: return "Ncipher Corp Ltd";
				case 0x0123: return "General Dynamics";
				case 0x018A: return "LevelOne";
				case 0x021B: return "Compaq Computer Corporation";
				case 0x0270: return "Hauppauge computer works Inc. (Wrong ID)";
				case 0x0291: return "Davicom Semiconductor, Inc.";
				case 0x02AC: return "SpeedStream";
				case 0x02E0: return "XFX Pine Group Inc";
				case 0x0303: return "Hewlett-Packard Company (Wrong ID)";
				case 0x0315: return "SK-Electronics Co., Ltd.";
				case 0x0357: return "TTTech AG";
				case 0x036F: return "Trigem Computer Inc.";
				case 0x0403: return "Future Technology Devices International Ltd";
				case 0x0432: return "SCM Microsystems, Inc.";
				case 0x045E: return "Microsoft";
				case 0x0482: return "Kyocera";
				case 0x04CF: return "Myson Century, Inc";
				case 0x050D: return "Belkin";
				case 0x058F: return "Alcor Micro Corporation";
				case 0x05A9: return "OmniVision";
				case 0x05E3: return "CyberDoor";
				case 0x066F: return "Sigmatel Inc.";
				case 0x0675: return "Dynalink";
				case 0x069D: return "Hughes Network Systems (HNS)";
				case 0x0721: return "Sapphire, Inc.";
				case 0x0795: return "Wired Inc.";
				case 0x07CA: return "AVerMedia Technologies Inc.";
				case 0x07D0: return "ITT Space Systems Division";
				case 0x07E2: return "ELMEG Communication Systems GmbH";
				case 0x0842: return "NPG, Personal Grand Technology";
				case 0x08E6: return "Gemalto NV";
				case 0x08FF: return "AuthenTec";
				case 0x0925: return "First International Computer, Inc.";
				case 0x093A: return "PixArt Imaging Inc.";
				case 0x09C1: return "Arris";
				case 0x0A89: return "BREA Technologies Inc";
				case 0x0ACE: return "ZyDAS";
				case 0x0B0B: return "Rhino Equipment Corp.";
				case 0x0B3D: return "Brontes Technologies";
				case 0x0B49: return "ASCII Corporation";
				case 0x0CCD: return "TerraTec Electronic GmbH";
				case 0x0E11: return "Compaq Computer Corporation";
				case 0x0E21: return "Cowon Systems, Inc.";
				case 0x0E55: return "HaSoTec GmbH";
				case 0x0EAC: return "SHF Communication Technologies AG";
				case 0x0F62: return "Acrox Technologies Co., Ltd.";
				case 0x1000: return "LSI Logic / Symbios Logic";
				case 0x1001: return "Kolter Electronic";
				case 0x1002: return "ATI Technologies Inc";
				case 0x1003: return "ULSI Systems";
				case 0x1004: return "VLSI Technology Inc";
				case 0x1005: return "Avance Logic Inc. [ALI]";
				case 0x1006: return "Reply Group";
				case 0x1007: return "NetFrame Systems Inc";
				case 0x1008: return "Epson";
				case 0x100A: return "Phoenix Technologies";
				case 0x100B: return "National Semiconductor Corporation";
				case 0x100C: return "Tseng Labs Inc";
				case 0x100D: return "AST Research Inc";
				case 0x100E: return "Weitek";
				case 0x1010: return "Video Logic, Ltd.";
				case 0x1011: return "Digital Equipment Corporation";
				case 0x1012: return "Micronics Computers Inc";
				case 0x1013: return "Cirrus Logic";
				case 0x1014: return "IBM";
				case 0x1015: return "LSI Logic Corp of Canada";
				case 0x1016: return "ICL Personal Systems";
				case 0x1017: return "SPEA Software AG";
				case 0x1018: return "Unisys Systems";
				case 0x1019: return "Elitegroup Computer Systems";
				case 0x101A: return "AT&T GIS (NCR)";
				case 0x101B: return "Vitesse Semiconductor";
				case 0x101C: return "Western Digital";
				case 0x101D: return "Maxim Integrated Products";
				case 0x101E: return "American Megatrends Inc.";
				case 0x101F: return "PictureTel";
				case 0x1020: return "Hitachi Computer Products";
				case 0x1021: return "OKI Electric Industry Co. Ltd.";
				case 0x1022: return "Advanced Micro Devices [AMD]";
				case 0x1023: return "Trident Microsystems";
				case 0x1024: return "Zenith Data Systems";
				case 0x1025: return "Acer Incorporated [ALI]";
				case 0x1028: return "Dell";
				case 0x1029: return "Siemens Nixdorf IS";
				case 0x102A: return "LSI Logic";
				case 0x102B: return "Matrox Graphics, Inc.";
				case 0x102C: return "Chips and Technologies";
				case 0x102D: return "Wyse Technology Inc.";
				case 0x102E: return "Olivetti Advanced Technology";
				case 0x102F: return "Toshiba America";
				case 0x1030: return "TMC Research";
				case 0x1031: return "Miro Computer Products AG";
				case 0x1032: return "Compaq";
				case 0x1033: return "NEC Corporation";
				case 0x1034: return "Framatome Connectors USA Inc.";
				case 0x1035: return "Comp. & Comm. Research Lab";
				case 0x1036: return "Future Domain Corp.";
				case 0x1037: return "Hitachi Micro Systems";
				case 0x1038: return "AMP, Inc";
				case 0x1039: return "Silicon Integrated Systems [SiS]";
				case 0x103A: return "Seiko Epson Corporation";
				case 0x103B: return "Tatung Corp. Of America";
				case 0x103C: return "Hewlett-Packard Company";
				case 0x103E: return "Solliday Engineering";
				case 0x103F: return "Synopsys/Logic Modeling Group";
				case 0x1040: return "Accelgraphics Inc.";
				case 0x1041: return "Computrend";
				case 0x1042: return "Micron";
				case 0x1043: return "ASUSTeK Computer Inc.";
				case 0x1044: return "Adaptec (formerly DPT)";
				case 0x1045: return "OPTi Inc.";
				case 0x1046: return "IPC Corporation, Ltd.";
				case 0x1047: return "Genoa Systems Corp";
				case 0x1048: return "Elsa AG";
				case 0x1049: return "Fountain Technologies, Inc.";
				case 0x104A: return "STMicroelectronics";
				case 0x104B: return "BusLogic";
				case 0x104C: return "Texas Instruments";
				case 0x104D: return "Sony Corporation";
				case 0x104E: return "Oak Technology, Inc";
				case 0x104F: return "Co-time Computer Ltd";
				case 0x1050: return "Winbond Electronics Corp";
				case 0x1051: return "Anigma, Inc.";
				case 0x1052: return "?Young Micro Systems";
				case 0x1053: return "Young Micro Systems";
				case 0x1054: return "Hitachi, Ltd";
				case 0x1055: return "Efar Microsystems";
				case 0x1056: return "ICL";
				case 0x1057: return "Motorola";
				case 0x1058: return "Electronics & Telecommunications RSH";
				case 0x1059: return "Kontron";
				case 0x105A: return "Promise Technology, Inc.";
				case 0x105B: return "Foxconn International, Inc.";
				case 0x105C: return "Wipro Infotech Limited";
				case 0x105D: return "Number 9 Computer Company";
				case 0x105E: return "Vtech Computers Ltd";
				case 0x105F: return "Infotronic America Inc";
				case 0x1060: return "United Microelectronics [UMC]";
				case 0x1061: return "I.I.T.";
				case 0x1062: return "Maspar Computer Corp";
				case 0x1063: return "Ocean Office Automation";
				case 0x1064: return "Alcatel";
				case 0x1065: return "Texas Microsystems";
				case 0x1066: return "PicoPower Technology";
				case 0x1067: return "Mitsubishi Electric";
				case 0x1068: return "Diversified Technology";
				case 0x1069: return "Mylex Corporation";
				case 0x106A: return "Aten Research Inc";
				case 0x106B: return "Apple Computer Inc.";
				case 0x106C: return "Hynix Semiconductor";
				case 0x106D: return "Sequent Computer Systems";
				case 0x106E: return "DFI, Inc";
				case 0x106F: return "City Gate Development Ltd";
				case 0x1070: return "Daewoo Telecom Ltd";
				case 0x1071: return "Mitac";
				case 0x1072: return "GIT Co Ltd";
				case 0x1073: return "Yamaha Corporation";
				case 0x1074: return "NexGen Microsystems";
				case 0x1075: return "Advanced Integrations Research";
				case 0x1076: return "Chaintech Computer Co. Ltd";
				case 0x1077: return "QLogic Corp.";
				case 0x1078: return "Cyrix Corporation";
				case 0x1079: return "I-Bus";
				case 0x107A: return "NetWorth";
				case 0x107B: return "Gateway 2000";
				case 0x107C: return "LG Electronics [Lucky Goldstar Co. Ltd]";
				case 0x107D: return "LeadTek Research Inc.";
				case 0x107E: return "Interphase Corporation";
				case 0x107F: return "Data Technology Corporation";
				case 0x1080: return "Contaq Microsystems";
				case 0x1081: return "Supermac Technology";
				case 0x1082: return "EFA Corporation of America";
				case 0x1083: return "Forex Computer Corporation";
				case 0x1084: return "Parador";
				case 0x1085: return "Tulip Computers Int.B.V.";
				case 0x1086: return "J. Bond Computer Systems";
				case 0x1087: return "Cache Computer";
				case 0x1088: return "Microcomputer Systems (M) Son";
				case 0x1089: return "Data General Corporation";
				case 0x108A: return "SBS Technologies";
				case 0x108C: return "Oakleigh Systems Inc.";
				case 0x108D: return "Olicom";
				case 0x108E: return "Sun Microsystems Computer Corp.";
				case 0x108F: return "Systemsoft";
				case 0x1090: return "Compro Computer Services, Inc.";
				case 0x1091: return "Intergraph Corporation";
				case 0x1092: return "Diamond Multimedia Systems";
				case 0x1093: return "National Instruments";
				case 0x1094: return "First International Computers [FIC]";
				case 0x1095: return "Silicon Image, Inc.";
				case 0x1096: return "Alacron";
				case 0x1097: return "Appian Technology";
				case 0x1098: return "Quantum Designs (H.K.) Ltd";
				case 0x1099: return "Samsung Electronics Co., Ltd";
				case 0x109A: return "Packard Bell";
				case 0x109B: return "Gemlight Computer Ltd.";
				case 0x109C: return "Megachips Corporation";
				case 0x109D: return "Zida Technologies Ltd.";
				case 0x109E: return "Brooktree Corporation";
				case 0x109F: return "Trigem Computer Inc.";
				case 0x10A0: return "Meidensha Corporation";
				case 0x10A1: return "Juko Electronics Ind. Co. Ltd";
				case 0x10A2: return "Quantum Corporation";
				case 0x10A3: return "Everex Systems Inc";
				case 0x10A4: return "Globe Manufacturing Sales";
				case 0x10A5: return "Smart Link Ltd.";
				case 0x10A6: return "Informtech Industrial Ltd.";
				case 0x10A7: return "Benchmarq Microelectronics";
				case 0x10A8: return "Sierra Semiconductor";
				case 0x10A9: return "Silicon Graphics, Inc.";
				case 0x10AA: return "ACC Microelectronics";
				case 0x10AB: return "Digicom";
				case 0x10AC: return "Honeywell IAC";
				case 0x10AD: return "Symphony Labs";
				case 0x10AE: return "Cornerstone Technology";
				case 0x10AF: return "Micro Computer Systems Inc";
				case 0x10B0: return "CardExpert Technology";
				case 0x10B1: return "Cabletron Systems Inc";
				case 0x10B2: return "Raytheon Company";
				case 0x10B3: return "Databook Inc";
				case 0x10B4: return "STB Systems Inc";
				case 0x10B5: return "PLX Technology, Inc.";
				case 0x10B6: return "Madge Networks";
				case 0x10B7: return "3Com Corporation";
				case 0x10B8: return "Standard Microsystems Corp [SMC]";
				case 0x10B9: return "ALi Corporation";
				case 0x10BA: return "Mitsubishi Electric Corp.";
				case 0x10BB: return "Dapha Electronics Corporation";
				case 0x10BC: return "Advanced Logic Research";
				case 0x10BD: return "Surecom Technology";
				case 0x10BE: return "Tseng Labs International Co.";
				case 0x10BF: return "Most Inc";
				case 0x10C0: return "Boca Research Inc.";
				case 0x10C1: return "ICM Co., Ltd.";
				case 0x10C2: return "Auspex Systems Inc.";
				case 0x10C3: return "Samsung Semiconductors, Inc.";
				case 0x10C4: return "Award Software International Inc.";
				case 0x10C5: return "Xerox Corporation";
				case 0x10C6: return "Rambus Inc.";
				case 0x10C7: return "Media Vision";
				case 0x10C8: return "Neomagic Corporation";
				case 0x10C9: return "Dataexpert Corporation";
				case 0x10CA: return "Fujitsu Microelectr., Inc.";
				case 0x10CB: return "Omron Corporation";
				case 0x10CC: return "Mai Logic Incorporated";
				case 0x10CD: return "Advanced System Products, Inc";
				case 0x10CE: return "Radius";
				case 0x10CF: return "Fujitsu Limited.";
				case 0x10D1: return "FuturePlus Systems Corp.";
				case 0x10D2: return "Molex Incorporated";
				case 0x10D3: return "Jabil Circuit Inc";
				case 0x10D4: return "Hualon Microelectronics";
				case 0x10D5: return "Autologic Inc.";
				case 0x10D6: return "Cetia";
				case 0x10D7: return "BCM Advanced Research";
				case 0x10D8: return "Advanced Peripherals Labs";
				case 0x10D9: return "Macronix, Inc. [MXIC]";
				case 0x10DA: return "Compaq IPG-Austin";
				case 0x10DB: return "Rohm LSI Systems, Inc.";
				case 0x10DC: return "CERN/ECP/EDU";
				case 0x10DD: return "Evans & Sutherland";
				case 0x10DE: return "nVidia Corporation";
				case 0x10DF: return "Emulex Corporation";
				case 0x10E0: return "Integrated Micro Solutions Inc.";
				case 0x10E1: return "Tekram Technology Co.,Ltd.";
				case 0x10E2: return "Aptix Corporation";
				case 0x10E3: return "Tundra Semiconductor Corp.";
				case 0x10E4: return "Tandem Computers";
				case 0x10E5: return "Micro Industries Corporation";
				case 0x10E6: return "Gainbery Computer Products Inc.";
				case 0x10E7: return "Vadem";
				case 0x10E8: return "Applied Micro Circuits Corp.";
				case 0x10E9: return "Alps Electric Co., Ltd.";
				case 0x10EA: return "Intergraphics Systems";
				case 0x10EB: return "Artists Graphics";
				case 0x10EC: return "Realtek Semiconductor Co., Ltd.";
				case 0x10ED: return "Ascii Corporation";
				case 0x10EE: return "Xilinx Corporation";
				case 0x10EF: return "Racore Computer Products, Inc.";
				case 0x10F0: return "Peritek Corporation";
				case 0x10F1: return "Tyan Computer";
				case 0x10F2: return "Achme Computer, Inc.";
				case 0x10F3: return "Alaris, Inc.";
				case 0x10F4: return "S-MOS Systems, Inc.";
				case 0x10F5: return "NKK Corporation";
				case 0x10F6: return "Creative Electronic Systems SA";
				case 0x10F7: return "Matsushita Electric Industrial Co., Ltd.";
				case 0x10F8: return "Altos India Ltd";
				case 0x10F9: return "PC Direct";
				case 0x10FA: return "Truevision";
				case 0x10FB: return "Thesys Gesellschaft fuer Mikroelektronik mbH";
				case 0x10FC: return "I-O Data Device, Inc.";
				case 0x10FD: return "Soyo Computer, Inc";
				case 0x10FE: return "Fast Multimedia AG";
				case 0x10FF: return "NCube";
				case 0x1100: return "Jazz Multimedia";
				case 0x1101: return "Initio Corporation";
				case 0x1102: return "Creative Labs";
				case 0x1103: return "HighPoint Technologies, Inc.";
				case 0x1104: return "RasterOps Corp.";
				case 0x1105: return "Sigma Designs, Inc.";
				case 0x1106: return "VIA Technologies, Inc.";
				case 0x1107: return "Stratus Computers";
				case 0x1108: return "Proteon, Inc.";
				case 0x1109: return "Cogent Data Technologies, Inc.";
				case 0x110A: return "Siemens Nixdorf AG";
				case 0x110B: return "Chromatic Research Inc.";
				case 0x110C: return "Mini-Max Technology, Inc.";
				case 0x110D: return "Znyx Advanced Systems";
				case 0x110E: return "CPU Technology";
				case 0x110F: return "Ross Technology";
				case 0x1110: return "Powerhouse Systems";
				case 0x1111: return "Santa Cruz Operation";
				case 0x1112: return "Osicom Technologies Inc";
				case 0x1113: return "Accton Technology Corporation";
				case 0x1114: return "Atmel Corporation";
				case 0x1115: return "3D Labs";
				case 0x1116: return "Data Translation";
				case 0x1117: return "Datacube, Inc";
				case 0x1118: return "Berg Electronics";
				case 0x1119: return "ICP Vortex Computersysteme GmbH";
				case 0x111A: return "Efficient Networks, Inc";
				case 0x111B: return "Teledyne Electronic Systems";
				case 0x111C: return "Tricord Systems Inc.";
				case 0x111D: return "Integrated Device Technology, Inc.";
				case 0x111E: return "Eldec";
				case 0x111F: return "Precision Digital Images";
				case 0x1120: return "EMC Corporation";
				case 0x1121: return "Zilog";
				case 0x1122: return "Multi-tech Systems, Inc.";
				case 0x1123: return "Excellent Design, Inc.";
				case 0x1124: return "Leutron Vision AG";
				case 0x1125: return "Eurocore";
				case 0x1126: return "Vigra";
				case 0x1127: return "FORE Systems Inc";
				case 0x1129: return "Firmworks";
				case 0x112A: return "Hermes Electronics Company, Ltd.";
				case 0x112B: return "Linotype - Hell AG";
				case 0x112C: return "Zenith Data Systems";
				case 0x112D: return "Ravicad";
				case 0x112E: return "Infomedia Microelectronics Inc.";
				case 0x112F: return "Dalsa Inc.";
				case 0x1130: return "Computervision";
				case 0x1131: return "Philips Semiconductors";
				case 0x1132: return "Mitel Corp.";
				case 0x1133: return "Dialogic Corporation";
				case 0x1134: return "Mercury Computer Systems";
				case 0x1135: return "Fuji Xerox Co Ltd";
				case 0x1136: return "Momentum Data Systems";
				case 0x1137: return "Cisco Systems Inc";
				case 0x1138: return "Ziatech Corporation";
				case 0x1139: return "Dynamic Pictures, Inc";
				case 0x113A: return "FWB Inc";
				case 0x113B: return "Network Computing Devices";
				case 0x113C: return "Cyclone Microsystems, Inc.";
				case 0x113D: return "Leading Edge Products Inc";
				case 0x113E: return "Sanyo Electric Co - Computer Engineering Dept";
				case 0x113F: return "Equinox Systems, Inc.";
				case 0x1140: return "Intervoice Inc";
				case 0x1141: return "Crest Microsystem Inc";
				case 0x1142: return "Alliance Semiconductor Corporation";
				case 0x1143: return "NetPower, Inc";
				case 0x1144: return "Cincinnati Milacron";
				case 0x1145: return "Workbit Corporation";
				case 0x1146: return "Force Computers";
				case 0x1147: return "Interface Corp";
				case 0x1148: return "SysKonnect";
				case 0x1149: return "Win System Corporation";
				case 0x114A: return "VMIC";
				case 0x114B: return "Canopus Co., Ltd";
				case 0x114C: return "Annabooks";
				case 0x114D: return "IC Corporation";
				case 0x114E: return "Nikon Systems Inc";
				case 0x114F: return "Digi International";
				case 0x1150: return "Thinking Machines Corp";
				case 0x1151: return "JAE Electronics Inc.";
				case 0x1152: return "Megatek";
				case 0x1153: return "Land Win Electronic Corp";
				case 0x1154: return "Melco Inc";
				case 0x1155: return "Pine Technology Ltd";
				case 0x1156: return "Periscope Engineering";
				case 0x1157: return "Avsys Corporation";
				case 0x1158: return "Voarx R & D Inc";
				case 0x1159: return "Mutech Corp";
				case 0x115A: return "Harlequin Ltd";
				case 0x115B: return "Parallax Graphics";
				case 0x115C: return "Photron Ltd.";
				case 0x115D: return "Xircom";
				case 0x115E: return "Peer Protocols Inc";
				case 0x115F: return "Maxtor Corporation";
				case 0x1160: return "Megasoft Inc";
				case 0x1161: return "PFU Limited";
				case 0x1162: return "OA Laboratory Co Ltd";
				case 0x1163: return "Rendition";
				case 0x1164: return "Advanced Peripherals Technologies";
				case 0x1165: return "Imagraph Corporation";
				case 0x1166: return "Broadcom";
				case 0x1167: return "Mutoh Industries Inc";
				case 0x1168: return "Thine Electronics Inc";
				case 0x1169: return "Centre for Development of Advanced Computing";
				case 0x116A: return "Luminex Software, Inc.";
				case 0x116B: return "Connectware Inc";
				case 0x116C: return "Intelligent Resources Integrated Systems";
				case 0x116D: return "Martin-Marietta";
				case 0x116E: return "Electronics for Imaging";
				case 0x116F: return "Workstation Technology";
				case 0x1170: return "Inventec Corporation";
				case 0x1171: return "Loughborough Sound Images Plc";
				case 0x1172: return "Altera Corporation";
				case 0x1173: return "Adobe Systems, Inc";
				case 0x1174: return "Bridgeport Machines";
				case 0x1175: return "Mitron Computer Inc.";
				case 0x1176: return "SBE Incorporated";
				case 0x1177: return "Silicon Engineering";
				case 0x1178: return "Alfa, Inc.";
				case 0x1179: return "Toshiba America Info Systems";
				case 0x117A: return "A-Trend Technology";
				case 0x117B: return "L G Electronics, Inc.";
				case 0x117C: return "Atto Technology";
				case 0x117D: return "Becton & Dickinson";
				case 0x117E: return "T/R Systems";
				case 0x117F: return "Integrated Circuit Systems";
				case 0x1180: return "Ricoh Co Ltd";
				case 0x1181: return "Telmatics International";
				case 0x1183: return "Fujikura Ltd";
				case 0x1184: return "Forks Inc";
				case 0x1185: return "Dataworld International Ltd";
				case 0x1186: return "D-Link System Inc";
				case 0x1187: return "Advanced Technology Laboratories, Inc.";
				case 0x1188: return "Shima Seiki Manufacturing Ltd.";
				case 0x1189: return "Matsushita Electronics Co Ltd";
				case 0x118A: return "Hilevel Technology";
				case 0x118B: return "Hypertec Pty Limited";
				case 0x118C: return "Corollary, Inc";
				case 0x118D: return "BitFlow Inc";
				case 0x118E: return "Hermstedt GmbH";
				case 0x118F: return "Green Logic";
				case 0x1190: return "Tripace";
				case 0x1191: return "Artop Electronic Corp";
				case 0x1192: return "Densan Company Ltd";
				case 0x1193: return "Zeitnet Inc.";
				case 0x1194: return "Toucan Technology";
				case 0x1195: return "Ratoc System Inc";
				case 0x1196: return "Hytec Electronics Ltd";
				case 0x1197: return "Gage Applied Sciences, Inc.";
				case 0x1198: return "Lambda Systems Inc";
				case 0x1199: return "Attachmate Corporation";
				case 0x119A: return "Mind Share, Inc.";
				case 0x119B: return "Omega Micro Inc.";
				case 0x119C: return "Information Technology Inst.";
				case 0x119D: return "Bug, Inc. Sapporo Japan";
				case 0x119E: return "Fujitsu Microelectronics Ltd.";
				case 0x119F: return "Bull HN Information Systems";
				case 0x11A0: return "Convex Computer Corporation";
				case 0x11A1: return "Hamamatsu Photonics K.K.";
				case 0x11A2: return "Sierra Research and Technology";
				case 0x11A3: return "Deuretzbacher GmbH & Co. Eng. KG";
				case 0x11A4: return "Barco Graphics NV";
				case 0x11A5: return "Microunity Systems Eng. Inc";
				case 0x11A6: return "Pure Data Ltd.";
				case 0x11A7: return "Power Computing Corp.";
				case 0x11A8: return "Systech Corp.";
				case 0x11A9: return "InnoSys Inc.";
				case 0x11AA: return "Actel";
				case 0x11AB: return "Marvell Technology Group Ltd.";
				case 0x11AC: return "Canon Information Systems Research Aust.";
				case 0x11AD: return "Lite-On Communications Inc";
				case 0x11AE: return "Aztech System Ltd";
				case 0x11AF: return "Avid Technology Inc.";
				case 0x11B0: return "V3 Semiconductor Inc.";
				case 0x11B1: return "Apricot Computers";
				case 0x11B2: return "Eastman Kodak";
				case 0x11B3: return "Barr Systems Inc.";
				case 0x11B4: return "Leitch Technology International";
				case 0x11B5: return "Radstone Technology Plc";
				case 0x11B6: return "United Video Corp";
				case 0x11B7: return "Motorola";
				case 0x11B8: return "XPoint Technologies, Inc";
				case 0x11B9: return "Pathlight Technology Inc.";
				case 0x11BA: return "Videotron Corp";
				case 0x11BB: return "Pyramid Technology";
				case 0x11BC: return "Network Peripherals Inc";
				case 0x11BD: return "Pinnacle Systems Inc.";
				case 0x11BE: return "International Microcircuits Inc";
				case 0x11BF: return "Astrodesign, Inc.";
				case 0x11C0: return "Hewlett Packard";
				case 0x11C1: return "Agere Systems";
				case 0x11C2: return "Sand Microelectronics";
				case 0x11C3: return "NEC Corporation";
				case 0x11C4: return "Document Technologies, Inc";
				case 0x11C5: return "Shiva Corporation";
				case 0x11C6: return "Dainippon Screen Mfg. Co. Ltd";
				case 0x11C7: return "D.C.M. Data Systems";
				case 0x11C8: return "Dolphin Interconnect Solutions AS";
				case 0x11C9: return "Magma";
				case 0x11CA: return "LSI Systems, Inc";
				case 0x11CB: return "Specialix Research Ltd.";
				case 0x11CC: return "Michels & Kleberhoff Computer GmbH";
				case 0x11CD: return "HAL Computer Systems, Inc.";
				case 0x11CE: return "Netaccess";
				case 0x11CF: return "Pioneer Electronic Corporation";
				case 0x11D0: return "Lockheed Martin Federal Systems-Manassas";
				case 0x11D1: return "Auravision";
				case 0x11D2: return "Intercom Inc.";
				case 0x11D3: return "Trancell Systems Inc";
				case 0x11D4: return "Analog Devices";
				case 0x11D5: return "Ikon Corporation";
				case 0x11D6: return "Tekelec Telecom";
				case 0x11D7: return "Trenton Technology, Inc.";
				case 0x11D8: return "Image Technologies Development";
				case 0x11D9: return "TEC Corporation";
				case 0x11DA: return "Novell";
				case 0x11DB: return "Sega Enterprises Ltd";
				case 0x11DC: return "Questra Corporation";
				case 0x11DD: return "Crosfield Electronics Limited";
				case 0x11DE: return "Zoran Corporation";
				case 0x11DF: return "New Wave PDG";
				case 0x11E0: return "Cray Communications A/S";
				case 0x11E1: return "GEC Plessey Semi Inc.";
				case 0x11E2: return "Samsung Information Systems America";
				case 0x11E3: return "Quicklogic Corporation";
				case 0x11E4: return "Second Wave Inc";
				case 0x11E5: return "IIX Consulting";
				case 0x11E6: return "Mitsui-Zosen System Research";
				case 0x11E7: return "Toshiba America, Elec. Company";
				case 0x11E8: return "Digital Processing Systems Inc.";
				case 0x11E9: return "Highwater Designs Ltd.";
				case 0x11EA: return "Elsag Bailey";
				case 0x11EB: return "Formation Inc.";
				case 0x11EC: return "Coreco Inc";
				case 0x11ED: return "Mediamatics";
				case 0x11EE: return "Dome Imaging Systems Inc";
				case 0x11EF: return "Nicolet Technologies B.V.";
				case 0x11F0: return "Compu-Shack";
				case 0x11F1: return "Symbios Logic Inc";
				case 0x11F2: return "Picture Tel Japan K.K.";
				case 0x11F3: return "Keithley Metrabyte";
				case 0x11F4: return "Kinetic Systems Corporation";
				case 0x11F5: return "Computing Devices International";
				case 0x11F6: return "Compex";
				case 0x11F7: return "Scientific Atlanta";
				case 0x11F8: return "PMC-Sierra Inc.";
				case 0x11F9: return "I-Cube Inc";
				case 0x11FA: return "Kasan Electronics Company, Ltd.";
				case 0x11FB: return "Datel Inc";
				case 0x11FC: return "Silicon Magic";
				case 0x11FD: return "High Street Consultants";
				case 0x11FE: return "Comtrol Corporation";
				case 0x11FF: return "Scion Corporation";
				case 0x1200: return "CSS Corporation";
				case 0x1201: return "Vista Controls Corp";
				case 0x1202: return "Network General Corp.";
				case 0x1203: return "Bayer Corporation, Agfa Division";
				case 0x1204: return "Lattice Semiconductor Corporation";
				case 0x1205: return "Array Corporation";
				case 0x1206: return "Amdahl Corporation";
				case 0x1208: return "Parsytec GmbH";
				case 0x1209: return "SCI Systems Inc";
				case 0x120A: return "Synaptel";
				case 0x120B: return "Adaptive Solutions";
				case 0x120C: return "Technical Corp.";
				case 0x120D: return "Compression Labs, Inc.";
				case 0x120E: return "Cyclades Corporation";
				case 0x120F: return "Essential Communications";
				case 0x1210: return "Hyperparallel Technologies";
				case 0x1211: return "Braintech Inc";
				case 0x1212: return "Kingston Technology Corp.";
				case 0x1213: return "Applied Intelligent Systems, Inc.";
				case 0x1214: return "Performance Technologies, Inc.";
				case 0x1215: return "Interware Co., Ltd";
				case 0x1216: return "Purup Prepress A/S";
				case 0x1217: return "O2 Micro, Inc.";
				case 0x1218: return "Hybricon Corp.";
				case 0x1219: return "First Virtual Corporation";
				case 0x121A: return "3Dfx Interactive, Inc.";
				case 0x121B: return "Advanced Telecommunications Modules";
				case 0x121C: return "Nippon Texaco., Ltd";
				case 0x121D: return "Lippert Automationstechnik GmbH";
				case 0x121E: return "CSPI";
				case 0x121F: return "Arcus Technology, Inc.";
				case 0x1220: return "Ariel Corporation";
				case 0x1221: return "Contec Co., Ltd";
				case 0x1222: return "Ancor Communications, Inc.";
				case 0x1223: return "Artesyn Communication Products";
				case 0x1224: return "Interactive Images";
				case 0x1225: return "Power I/O, Inc.";
				case 0x1227: return "Tech-Source";
				case 0x1228: return "Norsk Elektro Optikk A/S";
				case 0x1229: return "Data Kinesis Inc.";
				case 0x122A: return "Integrated Telecom";
				case 0x122B: return "LG Industrial Systems Co., Ltd";
				case 0x122C: return "Sican GmbH";
				case 0x122D: return "Aztech System Ltd";
				case 0x122E: return "Xyratex";
				case 0x122F: return "Andrew Corporation";
				case 0x1230: return "Fishcamp Engineering";
				case 0x1231: return "Woodward McCoach, Inc.";
				case 0x1232: return "GPT Limited";
				case 0x1233: return "Bus-Tech, Inc.";
				case 0x1234: return "Technical Corp.";
				case 0x1235: return "Risq Modular Systems, Inc.";
				case 0x1236: return "Sigma Designs Corporation";
				case 0x1237: return "Alta Technology Corporation";
				case 0x1238: return "Adtran";
				case 0x1239: return "3DO Company";
				case 0x123A: return "Visicom Laboratories, Inc.";
				case 0x123B: return "Seeq Technology, Inc.";
				case 0x123C: return "Century Systems, Inc.";
				case 0x123D: return "Engineering Design Team, Inc.";
				case 0x123E: return "Simutech, Inc.";
				case 0x123F: return "C-Cube Microsystems";
				case 0x1240: return "Marathon Technologies Corp.";
				case 0x1241: return "DSC Communications";
				case 0x1242: return "JNI Corporation";
				case 0x1243: return "Delphax";
				case 0x1244: return "AVM GmbH";
				case 0x1245: return "A.P.D., S.A.";
				case 0x1246: return "Dipix Technologies, Inc.";
				case 0x1247: return "Xylon Research, Inc.";
				case 0x1248: return "Central Data Corporation";
				case 0x1249: return "Samsung Electronics Co., Ltd.";
				case 0x124A: return "AEG Electrocom GmbH";
				case 0x124B: return "SBS/Greenspring Modular I/O";
				case 0x124C: return "Solitron Technologies, Inc.";
				case 0x124D: return "Stallion Technologies, Inc.";
				case 0x124E: return "Cylink";
				case 0x124F: return "Infortrend Technology, Inc.";
				case 0x1250: return "Hitachi Microcomputer System Ltd";
				case 0x1251: return "VLSI Solutions Oy";
				case 0x1253: return "Guzik Technical Enterprises";
				case 0x1254: return "Linear Systems Ltd.";
				case 0x1255: return "Optibase Ltd";
				case 0x1256: return "Perceptive Solutions, Inc.";
				case 0x1257: return "Vertex Networks, Inc.";
				case 0x1258: return "Gilbarco, Inc.";
				case 0x1259: return "Allied Telesyn International";
				case 0x125A: return "ABB Power Systems";
				case 0x125B: return "Asix Electronics Corporation";
				case 0x125C: return "Aurora Technologies, Inc.";
				case 0x125D: return "ESS Technology";
				case 0x125E: return "Specialvideo Engineering SRL";
				case 0x125F: return "Concurrent Technologies, Inc.";
				case 0x1260: return "Intersil Corporation";
				case 0x1261: return "Matsushita-Kotobuki Electronics Industries, Ltd.";
				case 0x1262: return "ES Computer Company, Ltd.";
				case 0x1263: return "Sonic Solutions";
				case 0x1264: return "Aval Nagasaki Corporation";
				case 0x1265: return "Casio Computer Co., Ltd.";
				case 0x1266: return "Microdyne Corporation";
				case 0x1267: return "S. A. Telecommunications";
				case 0x1268: return "Tektronix";
				case 0x1269: return "Thomson-CSF/TTM";
				case 0x126A: return "Lexmark International, Inc.";
				case 0x126B: return "Adax, Inc.";
				case 0x126C: return "Northern Telecom";
				case 0x126D: return "Splash Technology, Inc.";
				case 0x126E: return "Sumitomo Metal Industries, Ltd.";
				case 0x126F: return "Silicon Motion, Inc.";
				case 0x1270: return "Olympus Optical Co., Ltd.";
				case 0x1271: return "GW Instruments";
				case 0x1272: return "Telematics International";
				case 0x1273: return "Hughes Network Systems";
				case 0x1274: return "Ensoniq";
				case 0x1275: return "Network Appliance Corporation";
				case 0x1276: return "Switched Network Technologies, Inc.";
				case 0x1277: return "Comstream";
				case 0x1278: return "Transtech Parallel Systems Ltd.";
				case 0x1279: return "Transmeta Corporation";
				case 0x127A: return "Rockwell International";
				case 0x127B: return "Pixera Corporation";
				case 0x127C: return "Crosspoint Solutions, Inc.";
				case 0x127D: return "Vela Research";
				case 0x127E: return "Winnov, L.P.";
				case 0x127F: return "Fujifilm";
				case 0x1280: return "Photoscript Group Ltd.";
				case 0x1281: return "Yokogawa Electric Corporation";
				case 0x1282: return "Davicom Semiconductor, Inc.";
				case 0x1283: return "Integrated Technology Express, Inc.";
				case 0x1284: return "Sahara Networks, Inc.";
				case 0x1285: return "Platform Technologies, Inc.";
				case 0x1286: return "Mazet GmbH";
				case 0x1287: return "M-Pact, Inc.";
				case 0x1288: return "Timestep Corporation";
				case 0x1289: return "AVC Technology, Inc.";
				case 0x128A: return "Asante Technologies, Inc.";
				case 0x128B: return "Transwitch Corporation";
				case 0x128C: return "Retix Corporation";
				case 0x128D: return "G2 Networks, Inc.";
				case 0x128E: return "Hoontech Corporation/Samho Multi Tech Ltd.";
				case 0x128F: return "Tateno Dennou, Inc.";
				case 0x1290: return "Sord Computer Corporation";
				case 0x1291: return "NCS Computer Italia";
				case 0x1292: return "Tritech Microelectronics Inc";
				case 0x1293: return "Media Reality Technology";
				case 0x1294: return "Rhetorex, Inc.";
				case 0x1295: return "Imagenation Corporation";
				case 0x1296: return "Kofax Image Products";
				case 0x1297: return "Holco Enterprise Co, Ltd/Shuttle Computer";
				case 0x1298: return "Spellcaster Telecommunications Inc.";
				case 0x1299: return "Knowledge Technology Lab.";
				case 0x129A: return "VMetro, inc.";
				case 0x129B: return "Image Access";
				case 0x129C: return "Jaycor";
				case 0x129D: return "Compcore Multimedia, Inc.";
				case 0x129E: return "Victor Company of Japan, Ltd.";
				case 0x129F: return "OEC Medical Systems, Inc.";
				case 0x12A0: return "Allen-Bradley Company";
				case 0x12A1: return "Simpact Associates, Inc.";
				case 0x12A2: return "Newgen Systems Corporation";
				case 0x12A3: return "Lucent Technologies";
				case 0x12A4: return "NTT Electronics Technology Company";
				case 0x12A5: return "Vision Dynamics Ltd.";
				case 0x12A6: return "Scalable Networks, Inc.";
				case 0x12A7: return "AMO GmbH";
				case 0x12A8: return "News Datacom";
				case 0x12A9: return "Xiotech Corporation";
				case 0x12AA: return "SDL Communications, Inc.";
				case 0x12AB: return "Yuan Yuan Enterprise Co., Ltd.";
				case 0x12AC: return "Measurex Corporation";
				case 0x12AD: return "Multidata GmbH";
				case 0x12AE: return "Alteon Networks Inc.";
				case 0x12AF: return "TDK USA Corp";
				case 0x12B0: return "Jorge Scientific Corp";
				case 0x12B1: return "GammaLink";
				case 0x12B2: return "General Signal Networks";
				case 0x12B3: return "Inter-Face Co Ltd";
				case 0x12B4: return "FutureTel Inc";
				case 0x12B5: return "Granite Systems Inc.";
				case 0x12B6: return "Natural Microsystems";
				case 0x12B7: return "Cognex Modular Vision Systems Div. - Acumen Inc.";
				case 0x12B8: return "Korg";
				case 0x12B9: return "3Com Corp, Modem Division";
				case 0x12BA: return "BittWare, Inc.";
				case 0x12BB: return "Nippon Unisoft Corporation";
				case 0x12BC: return "Array Microsystems";
				case 0x12BD: return "Computerm Corp.";
				case 0x12BE: return "Anchor Chips Inc.";
				case 0x12BF: return "Fujifilm Microdevices";
				case 0x12C0: return "Infimed";
				case 0x12C1: return "GMM Research Corp";
				case 0x12C2: return "Mentec Limited";
				case 0x12C3: return "Holtek Microelectronics Inc";
				case 0x12C4: return "Connect Tech Inc";
				case 0x12C5: return "Picture Elements Incorporated";
				case 0x12C6: return "Mitani Corporation";
				case 0x12C7: return "Dialogic Corp";
				case 0x12C8: return "G Force Co, Ltd";
				case 0x12C9: return "Gigi Operations";
				case 0x12CA: return "Integrated Computing Engines";
				case 0x12CB: return "Antex Electronics Corporation";
				case 0x12CC: return "Pluto Technologies International";
				case 0x12CD: return "Aims Lab";
				case 0x12CE: return "Netspeed Inc.";
				case 0x12CF: return "Prophet Systems, Inc.";
				case 0x12D0: return "GDE Systems, Inc.";
				case 0x12D1: return "PSITech";
				case 0x12D2: return "NVidia / SGS Thomson (Joint Venture)";
				case 0x12D3: return "Vingmed Sound A/S";
				case 0x12D4: return "Ulticom (Formerly DGM&S)";
				case 0x12D5: return "Equator Technologies Inc";
				case 0x12D6: return "Analogic Corp";
				case 0x12D7: return "Biotronic SRL";
				case 0x12D8: return "Pericom Semiconductor";
				case 0x12D9: return "Aculab PLC";
				case 0x12DA: return "True Time Inc.";
				case 0x12DB: return "Annapolis Micro Systems, Inc";
				case 0x12DC: return "Symicron Computer Communication Ltd.";
				case 0x12DD: return "Management Graphics";
				case 0x12DE: return "Rainbow Technologies";
				case 0x12DF: return "SBS Technologies Inc";
				case 0x12E0: return "Chase Research";
				case 0x12E1: return "Nintendo Co, Ltd";
				case 0x12E2: return "Datum Inc. Bancomm-Timing Division";
				case 0x12E3: return "Imation Corp - Medical Imaging Systems";
				case 0x12E4: return "Brooktrout Technology Inc";
				case 0x12E5: return "Apex Semiconductor Inc";
				case 0x12E6: return "Cirel Systems";
				case 0x12E7: return "Sunsgroup Corporation";
				case 0x12E8: return "Crisc Corp";
				case 0x12E9: return "GE Spacenet";
				case 0x12EA: return "Zuken";
				case 0x12EB: return "Aureal Semiconductor";
				case 0x12EC: return "3A International, Inc.";
				case 0x12ED: return "Optivision Inc.";
				case 0x12EE: return "Orange Micro";
				case 0x12EF: return "Vienna Systems";
				case 0x12F0: return "Pentek";
				case 0x12F1: return "Sorenson Vision Inc";
				case 0x12F2: return "Gammagraphx, Inc.";
				case 0x12F3: return "Radstone Technology";
				case 0x12F4: return "Megatel";
				case 0x12F5: return "Forks";
				case 0x12F6: return "Dawson France";
				case 0x12F7: return "Cognex";
				case 0x12F8: return "Electronic Design GmbH";
				case 0x12F9: return "Four Fold Ltd";
				case 0x12FB: return "Spectrum Signal Processing";
				case 0x12FC: return "Capital Equipment Corp";
				case 0x12FD: return "I2S";
				case 0x12FE: return "ESD Electronic System Design GmbH";
				case 0x12FF: return "Lexicon";
				case 0x1300: return "Harman International Industries Inc";
				case 0x1302: return "Computer Sciences Corp";
				case 0x1303: return "Innovative Integration";
				case 0x1304: return "Juniper Networks";
				case 0x1305: return "Netphone, Inc";
				case 0x1306: return "Duet Technologies";
				case 0x1307: return "Measurement Computing";
				case 0x1308: return "Jato Technologies Inc.";
				case 0x1309: return "AB Semiconductor Ltd";
				case 0x130A: return "Mitsubishi Electric Microcomputer";
				case 0x130B: return "Colorgraphic Communications Corp";
				case 0x130C: return "Ambex Technologies, Inc";
				case 0x130D: return "Accelerix Inc";
				case 0x130E: return "Yamatake-Honeywell Co. Ltd";
				case 0x130F: return "Advanet Inc";
				case 0x1310: return "Gespac";
				case 0x1311: return "Videoserver, Inc";
				case 0x1312: return "Acuity Imaging, Inc";
				case 0x1313: return "Yaskawa Electric Co.";
				case 0x1315: return "Wavesat";
				case 0x1316: return "Teradyne Inc";
				case 0x1317: return "ADMtek";
				case 0x1318: return "Packet Engines Inc.";
				case 0x1319: return "Fortemedia, Inc";
				case 0x131A: return "Finisar Corp.";
				case 0x131C: return "Nippon Electro-Sensory Devices Corp";
				case 0x131D: return "Sysmic, Inc.";
				case 0x131E: return "Xinex Networks Inc";
				case 0x131F: return "Siig Inc";
				case 0x1320: return "Crypto AG";
				case 0x1321: return "Arcobel Graphics BV";
				case 0x1322: return "MTT Co., Ltd";
				case 0x1323: return "Dome Inc";
				case 0x1324: return "Sphere Communications";
				case 0x1325: return "Salix Technologies, Inc";
				case 0x1326: return "Seachange international";
				case 0x1327: return "Voss scientific";
				case 0x1328: return "quadrant international";
				case 0x1329: return "Productivity Enhancement";
				case 0x132A: return "Microcom Inc.";
				case 0x132B: return "Broadband Technologies";
				case 0x132C: return "Micrel Inc";
				case 0x132D: return "Integrated Silicon Solution, Inc.";
				case 0x1330: return "MMC Networks";
				case 0x1331: return "RadiSys Corporation";
				case 0x1332: return "Micro Memory";
				case 0x1334: return "Redcreek Communications, Inc";
				case 0x1335: return "Videomail, Inc";
				case 0x1337: return "Third Planet Publishing";
				case 0x1338: return "BT Electronics";
				case 0x133A: return "Vtel Corp";
				case 0x133B: return "Softcom Microsystems";
				case 0x133C: return "Holontech Corp";
				case 0x133D: return "SS Technologies";
				case 0x133E: return "Virtual Computer Corp";
				case 0x133F: return "SCM Microsystems";
				case 0x1340: return "Atalla Corp";
				case 0x1341: return "Kyoto Microcomputer Co";
				case 0x1342: return "Promax Systems Inc";
				case 0x1343: return "Phylon Communications Inc";
				case 0x1344: return "Crucial Technology";
				case 0x1345: return "Arescom Inc";
				case 0x1347: return "Odetics";
				case 0x1349: return "Sumitomo Electric Industries, Ltd.";
				case 0x134A: return "DTC Technology Corp.";
				case 0x134B: return "ARK Research Corp.";
				case 0x134C: return "Chori Joho System Co. Ltd";
				case 0x134D: return "PCTel Inc";
				case 0x134E: return "CSTI";
				case 0x134F: return "Algo System Co Ltd";
				case 0x1350: return "Systec Co. Ltd";
				case 0x1351: return "Sonix Inc";
				case 0x1353: return "Thales Idatys";
				case 0x1354: return "Dwave System Inc";
				case 0x1355: return "Kratos Analytical Ltd";
				case 0x1356: return "The Logical Co";
				case 0x1359: return "Prisa Networks";
				case 0x135A: return "Brain Boxes";
				case 0x135B: return "Giganet Inc";
				case 0x135C: return "Quatech Inc";
				case 0x135D: return "ABB Network Partner AB";
				case 0x135E: return "Sealevel Systems Inc";
				case 0x135F: return "I-Data International A-S";
				case 0x1360: return "Meinberg Funkuhren";
				case 0x1361: return "Soliton Systems K.K.";
				case 0x1362: return "Fujifacom Corporation";
				case 0x1363: return "Phoenix Technology Ltd";
				case 0x1364: return "ATM Communications Inc";
				case 0x1365: return "Hypercope GmbH";
				case 0x1366: return "Teijin Seiki Co. Ltd";
				case 0x1367: return "Hitachi Zosen Corporation";
				case 0x1368: return "Skyware Corporation";
				case 0x1369: return "Digigram";
				case 0x136A: return "High Soft Tech";
				case 0x136B: return "Kawasaki Steel Corporation";
				case 0x136C: return "Adtek System Science Co Ltd";
				case 0x136D: return "Gigalabs Inc";
				case 0x136F: return "Applied Magic Inc";
				case 0x1370: return "ATL Products";
				case 0x1371: return "CNet Technology Inc";
				case 0x1373: return "Silicon Vision Inc";
				case 0x1374: return "Silicom Ltd.";
				case 0x1375: return "Argosystems Inc";
				case 0x1376: return "LMC";
				case 0x1377: return "Electronic Equipment Production & Distribution GmbH";
				case 0x1378: return "Telemann Co. Ltd";
				case 0x1379: return "Asahi Kasei Microsystems Co Ltd";
				case 0x137A: return "Mark of the Unicorn Inc";
				case 0x137B: return "PPT Vision";
				case 0x137C: return "Iwatsu Electric Co Ltd";
				case 0x137D: return "Dynachip Corporation";
				case 0x137E: return "Patriot Scientific Corporation";
				case 0x137F: return "Japan Satellite Systems Inc";
				case 0x1380: return "Sanritz Automation Co Ltd";
				case 0x1381: return "Brains Co. Ltd";
				case 0x1382: return "Marian - Electronic & Software";
				case 0x1383: return "Controlnet Inc";
				case 0x1384: return "Reality Simulation Systems Inc";
				case 0x1385: return "Netgear";
				case 0x1386: return "Video Domain Technologies";
				case 0x1387: return "Systran Corp";
				case 0x1388: return "Hitachi Information Technology Co Ltd";
				case 0x1389: return "Applicom International";
				case 0x138A: return "Fusion Micromedia Corp";
				case 0x138B: return "Tokimec Inc";
				case 0x138C: return "Silicon Reality";
				case 0x138D: return "Future Techno Designs pte Ltd";
				case 0x138E: return "Basler GmbH";
				case 0x138F: return "Patapsco Designs Inc";
				case 0x1390: return "Concept Development Inc";
				case 0x1391: return "Development Concepts Inc";
				case 0x1392: return "Medialight Inc";
				case 0x1393: return "Moxa Technologies Co Ltd";
				case 0x1394: return "Level One Communications";
				case 0x1395: return "Ambicom Inc";
				case 0x1396: return "Cipher Systems Inc";
				case 0x1397: return "Cologne Chip Designs GmbH";
				case 0x1398: return "Clarion co. Ltd";
				case 0x1399: return "Rios systems Co Ltd";
				case 0x139A: return "Alacritech Inc";
				case 0x139B: return "Mediasonic Multimedia Systems Ltd";
				case 0x139C: return "Quantum 3d Inc";
				case 0x139D: return "EPL limited";
				case 0x139E: return "Media4";
				case 0x139F: return "Aethra s.r.l.";
				case 0x13A0: return "Crystal Group Inc";
				case 0x13A1: return "Kawasaki Heavy Industries Ltd";
				case 0x13A2: return "Ositech Communications Inc";
				case 0x13A3: return "Hifn Inc.";
				case 0x13A4: return "Rascom Inc";
				case 0x13A5: return "Audio Digital Imaging Inc";
				case 0x13A6: return "Videonics Inc";
				case 0x13A7: return "Teles AG";
				case 0x13A8: return "Exar Corp.";
				case 0x13A9: return "Siemens Medical Systems, Ultrasound Group";
				case 0x13AA: return "Broadband Networks Inc";
				case 0x13AB: return "Arcom Control Systems Ltd";
				case 0x13AC: return "Motion Media Technology Ltd";
				case 0x13AD: return "Nexus Inc";
				case 0x13AE: return "ALD Technology Ltd";
				case 0x13AF: return "T.Sqware";
				case 0x13B0: return "Maxspeed Corp";
				case 0x13B1: return "Tamura corporation";
				case 0x13B2: return "Techno Chips Co. Ltd";
				case 0x13B3: return "Lanart Corporation";
				case 0x13B4: return "Wellbean Co Inc";
				case 0x13B5: return "ARM";
				case 0x13B6: return "Dlog GmbH";
				case 0x13B7: return "Logic Devices Inc";
				case 0x13B8: return "Nokia Telecommunications oy";
				case 0x13B9: return "Elecom Co Ltd";
				case 0x13BA: return "Oxford Instruments";
				case 0x13BB: return "Sanyo Technosound Co Ltd";
				case 0x13BC: return "Bitran Corporation";
				case 0x13BD: return "Sharp corporation";
				case 0x13BE: return "Miroku Jyoho Service Co. Ltd";
				case 0x13BF: return "Sharewave Inc";
				case 0x13C0: return "Microgate Corporation";
				case 0x13C1: return "3ware Inc";
				case 0x13C2: return "Technotrend Systemtechnik GmbH";
				case 0x13C3: return "Janz Computer AG";
				case 0x13C4: return "Phase Metrics";
				case 0x13C5: return "Alphi Technology Corp";
				case 0x13C6: return "Condor Engineering Inc";
				case 0x13C7: return "Blue Chip Technology Ltd";
				case 0x13C8: return "Apptech Inc";
				case 0x13C9: return "Eaton Corporation";
				case 0x13CA: return "Iomega Corporation";
				case 0x13CB: return "Yano Electric Co Ltd";
				case 0x13CC: return "Metheus Corporation";
				case 0x13CD: return "Compatible Systems Corporation";
				case 0x13CE: return "Cocom A/S";
				case 0x13CF: return "Studio Audio & Video Ltd";
				case 0x13D0: return "Techsan Electronics Co Ltd";
				case 0x13D1: return "Abocom Systems Inc";
				case 0x13D2: return "Shark Multimedia Inc";
				case 0x13D3: return "IMC Networks";
				case 0x13D4: return "Graphics Microsystems Inc";
				case 0x13D5: return "Media 100 Inc";
				case 0x13D6: return "K.I. Technology Co Ltd";
				case 0x13D7: return "Toshiba Engineering Corporation";
				case 0x13D8: return "Phobos corporation";
				case 0x13D9: return "Apex PC Solutions Inc";
				case 0x13DA: return "Intresource Systems pte Ltd";
				case 0x13DB: return "Janich & Klass Computertechnik GmbH";
				case 0x13DC: return "Netboost Corporation";
				case 0x13DD: return "Multimedia Bundle Inc";
				case 0x13DE: return "ABB Robotics Products AB";
				case 0x13DF: return "E-Tech Inc";
				case 0x13E0: return "GVC Corporation";
				case 0x13E1: return "Silicom Multimedia Systems Inc";
				case 0x13E2: return "Dynamics Research Corporation";
				case 0x13E3: return "Nest Inc";
				case 0x13E4: return "Calculex Inc";
				case 0x13E5: return "Telesoft Design Ltd";
				case 0x13E6: return "Argosy research Inc";
				case 0x13E7: return "NAC Incorporated";
				case 0x13E8: return "Chip Express Corporation";
				case 0x13E9: return "Intraserver Technology Inc";
				case 0x13EA: return "Dallas Semiconductor";
				case 0x13EB: return "Hauppauge Computer Works Inc";
				case 0x13EC: return "Zydacron Inc";
				case 0x13ED: return "Raytheion E-Systems";
				case 0x13EE: return "Hayes Microcomputer Products Inc";
				case 0x13EF: return "Coppercom Inc";
				case 0x13F0: return "Sundance Technology Inc / IC Plus Corp";
				case 0x13F1: return "Oce' - Technologies B.V.";
				case 0x13F2: return "Ford Microelectronics Inc";
				case 0x13F3: return "Mcdata Corporation";
				case 0x13F4: return "Troika Networks, Inc.";
				case 0x13F5: return "Kansai Electric Co. Ltd";
				case 0x13F6: return "C-Media Electronics Inc";
				case 0x13F7: return "Wildfire Communications";
				case 0x13F8: return "Ad Lib Multimedia Inc";
				case 0x13F9: return "NTT Advanced Technology Corp.";
				case 0x13FA: return "Pentland Systems Ltd";
				case 0x13FB: return "Aydin Corp";
				case 0x13FC: return "Computer Peripherals International";
				case 0x13FD: return "Micro Science Inc";
				case 0x13FE: return "Advantech Co. Ltd";
				case 0x13FF: return "Silicon Spice Inc";
				case 0x1400: return "Artx Inc";
				case 0x1401: return "CR-Systems A/S";
				case 0x1402: return "Meilhaus Electronic GmbH";
				case 0x1403: return "Ascor Inc";
				case 0x1404: return "Fundamental Software Inc";
				case 0x1405: return "Excalibur Systems Inc";
				case 0x1406: return "Oce' Printing Systems GmbH";
				case 0x1407: return "Lava Computer mfg Inc";
				case 0x1408: return "Aloka Co. Ltd";
				case 0x1409: return "Timedia Technology Co Ltd";
				case 0x140A: return "DSP Research Inc";
				case 0x140B: return "Ramix Inc";
				case 0x140C: return "Elmic Systems Inc";
				case 0x140D: return "Matsushita Electric Works Ltd";
				case 0x140E: return "Goepel Electronic GmbH";
				case 0x140F: return "Salient Systems Corp";
				case 0x1410: return "Midas lab Inc";
				case 0x1411: return "Ikos Systems Inc";
				case 0x1412: return "VIA Technologies Inc.";
				case 0x1413: return "Addonics";
				case 0x1414: return "Microsoft Corporation";
				case 0x1415: return "Oxford Semiconductor Ltd";
				case 0x1416: return "Multiwave Innovation pte Ltd";
				case 0x1417: return "Convergenet Technologies Inc";
				case 0x1418: return "Kyushu electronics systems Inc";
				case 0x1419: return "Excel Switching Corp";
				case 0x141A: return "Apache Micro Peripherals Inc";
				case 0x141B: return "Zoom Telephonics Inc";
				case 0x141D: return "Digitan Systems Inc";
				case 0x141E: return "Fanuc Ltd";
				case 0x141F: return "Visiontech Ltd";
				case 0x1420: return "Psion Dacom plc";
				case 0x1421: return "Ads Technologies Inc";
				case 0x1422: return "Ygrec Systems Co Ltd";
				case 0x1423: return "Custom Technology Corp.";
				case 0x1424: return "Videoserver Connections";
				case 0x1425: return "Chelsio Communications Inc";
				case 0x1426: return "Storage Technology Corp.";
				case 0x1427: return "Better On-Line Solutions";
				case 0x1428: return "Edec Co Ltd";
				case 0x1429: return "Unex Technology Corp.";
				case 0x142A: return "Kingmax Technology Inc";
				case 0x142B: return "Radiolan";
				case 0x142C: return "Minton Optic Industry Co Ltd";
				case 0x142D: return "Pix stream Inc";
				case 0x142E: return "Vitec Multimedia";
				case 0x142F: return "Radicom Research Inc";
				case 0x1430: return "ITT Aerospace/Communications Division";
				case 0x1431: return "Gilat Satellite Networks";
				case 0x1432: return "Edimax Computer Co.";
				case 0x1433: return "Eltec Elektronik GmbH";
				case 0x1435: return "RTD Embedded Technologies, Inc.";
				case 0x1436: return "CIS Technology Inc";
				case 0x1437: return "Nissin Inc Co";
				case 0x1438: return "Atmel-dream";
				case 0x1439: return "Outsource Engineering & Mfg. Inc";
				case 0x143A: return "Stargate Solutions Inc";
				case 0x143B: return "Canon Research Center, America";
				case 0x143C: return "Amlogic Inc";
				case 0x143D: return "Tamarack Microelectronics Inc";
				case 0x143E: return "Jones Futurex Inc";
				case 0x143F: return "Lightwell Co Ltd - Zax Division";
				case 0x1440: return "ALGOL Corp.";
				case 0x1441: return "AGIE Ltd";
				case 0x1442: return "Phoenix Contact GmbH & Co.";
				case 0x1443: return "Unibrain S.A.";
				case 0x1444: return "TRW";
				case 0x1445: return "Logical DO Ltd";
				case 0x1446: return "Graphin Co Ltd";
				case 0x1447: return "AIM GmBH";
				case 0x1448: return "Alesis Studio Electronics";
				case 0x1449: return "TUT Systems Inc";
				case 0x144A: return "Adlink Technology";
				case 0x144B: return "Verint Systems Inc.";
				case 0x144C: return "Catalina Research Inc";
				case 0x144D: return "Samsung Electronics Co Ltd";
				case 0x144E: return "OLITEC";
				case 0x144F: return "Askey Computer Corp.";
				case 0x1450: return "Octave Communications Ind.";
				case 0x1451: return "SP3D Chip Design GmBH";
				case 0x1453: return "MYCOM Inc";
				case 0x1454: return "Altiga Networks";
				case 0x1455: return "Logic Plus Plus Inc";
				case 0x1456: return "Advanced Hardware Architectures";
				case 0x1457: return "Nuera Communications Inc";
				case 0x1458: return "Giga-byte Technology";
				case 0x1459: return "DOOIN Electronics";
				case 0x145A: return "Escalate Networks Inc";
				case 0x145B: return "PRAIM SRL";
				case 0x145C: return "Cryptek";
				case 0x145D: return "Gallant Computer Inc";
				case 0x145E: return "Aashima Technology B.V.";
				case 0x145F: return "Baldor Electric Company";
				case 0x1460: return "DYNARC INC";
				case 0x1461: return "Avermedia Technologies Inc";
				case 0x1462: return "Micro-Star International Co., Ltd.";
				case 0x1463: return "Fast Corporation";
				case 0x1464: return "Interactive Circuits & Systems Ltd";
				case 0x1465: return "GN NETTEST Telecom DIV.";
				case 0x1466: return "Designpro Inc.";
				case 0x1467: return "DIGICOM SPA";
				case 0x1468: return "AMBIT Microsystem Corp.";
				case 0x1469: return "Cleveland Motion Controls";
				case 0x146A: return "IFR";
				case 0x146B: return "Parascan Technologies Ltd";
				case 0x146C: return "Ruby Tech Corp.";
				case 0x146D: return "Tachyon, INC.";
				case 0x146E: return "Williams Electronics Games, Inc.";
				case 0x146F: return "Multi Dimensional Consulting Inc";
				case 0x1470: return "Bay Networks";
				case 0x1471: return "Integrated Telecom Express Inc";
				case 0x1472: return "DAIKIN Industries, Ltd";
				case 0x1473: return "ZAPEX Technologies Inc";
				case 0x1474: return "Doug Carson & Associates";
				case 0x1475: return "PICAZO Communications";
				case 0x1476: return "MORTARA Instrument Inc";
				case 0x1477: return "Net Insight";
				case 0x1478: return "DIATREND Corporation";
				case 0x1479: return "TORAY Industries Inc";
				case 0x147A: return "FORMOSA Industrial Computing";
				case 0x147B: return "ABIT Computer Corp.";
				case 0x147C: return "AWARE, Inc.";
				case 0x147D: return "Interworks Computer Products";
				case 0x147E: return "Matsushita Graphic Communication Systems, Inc.";
				case 0x147F: return "NIHON UNISYS, Ltd.";
				case 0x1480: return "SCII Telecom";
				case 0x1481: return "BIOPAC Systems Inc";
				case 0x1482: return "ISYTEC - Integrierte Systemtechnik GmBH";
				case 0x1483: return "LABWAY Corporation";
				case 0x1484: return "Logic Corporation";
				case 0x1485: return "ERMA - Electronic GmBH";
				case 0x1486: return "L3 Communications Telemetry & Instrumentation";
				case 0x1487: return "MARQUETTE Medical Systems";
				case 0x1488: return "KONTRON Electronik GmBH";
				case 0x1489: return "KYE Systems Corporation";
				case 0x148A: return "OPTO";
				case 0x148B: return "INNOMEDIALOGIC Inc.";
				case 0x148C: return "C.P. Technology Co. Ltd";
				case 0x148D: return "DIGICOM Systems, Inc.";
				case 0x148E: return "OSI Plus Corporation";
				case 0x148F: return "Plant Equipment, Inc.";
				case 0x1490: return "Stone Microsystems PTY Ltd.";
				case 0x1491: return "ZEAL Corporation";
				case 0x1492: return "Time Logic Corporation";
				case 0x1493: return "MAKER Communications";
				case 0x1494: return "WINTOP Technology, Inc.";
				case 0x1495: return "TOKAI Communications Industry Co. Ltd";
				case 0x1496: return "JOYTECH Computer Co., Ltd.";
				case 0x1497: return "SMA Regelsysteme GmBH";
				case 0x1498: return "TEWS Technologies GmbH";
				case 0x1499: return "EMTEC CO., Ltd";
				case 0x149A: return "ANDOR Technology Ltd";
				case 0x149B: return "SEIKO Instruments Inc";
				case 0x149C: return "OVISLINK Corp.";
				case 0x149D: return "NEWTEK Inc";
				case 0x149E: return "Mapletree Networks Inc.";
				case 0x149F: return "LECTRON Co Ltd";
				case 0x14A0: return "SOFTING GmBH";
				case 0x14A1: return "Systembase Co Ltd";
				case 0x14A2: return "Millennium Engineering Inc";
				case 0x14A3: return "Maverick Networks";
				case 0x14A4: return "GVC/BCM Advanced Research";
				case 0x14A5: return "XIONICS Document Technologies Inc";
				case 0x14A6: return "INOVA Computers GmBH & Co KG";
				case 0x14A7: return "MYTHOS Systems Inc";
				case 0x14A8: return "FEATRON Technologies Corporation";
				case 0x14A9: return "HIVERTEC Inc";
				case 0x14AA: return "Advanced MOS Technology Inc";
				case 0x14AB: return "Mentor Graphics Corp.";
				case 0x14AC: return "Novaweb Technologies Inc";
				case 0x14AD: return "Time Space Radio AB";
				case 0x14AE: return "CTI, Inc";
				case 0x14AF: return "Guillemot Corporation";
				case 0x14B0: return "BST Communication Technology Ltd";
				case 0x14B1: return "Nextcom K.K.";
				case 0x14B2: return "ENNOVATE Networks Inc";
				case 0x14B3: return "XPEED Inc";
				case 0x14B4: return "PHILIPS Business Electronics B.V.";
				case 0x14B5: return "Creamware GmBH";
				case 0x14B6: return "Quantum Data Corp.";
				case 0x14B7: return "PROXIM Inc";
				case 0x14B8: return "Techsoft Technology Co Ltd";
				case 0x14B9: return "AIRONET Wireless Communications";
				case 0x14BA: return "INTERNIX Inc.";
				case 0x14BB: return "SEMTECH Corporation";
				case 0x14BC: return "Globespan Semiconductor Inc.";
				case 0x14BD: return "CARDIO Control N.V.";
				case 0x14BE: return "L3 Communications";
				case 0x14BF: return "SPIDER Communications Inc.";
				case 0x14C0: return "COMPAL Electronics Inc";
				case 0x14C1: return "MYRICOM Inc.";
				case 0x14C2: return "DTK Computer";
				case 0x14C3: return "MEDIATEK Corp.";
				case 0x14C4: return "IWASAKI Information Systems Co Ltd";
				case 0x14C5: return "Automation Products AB";
				case 0x14C6: return "Data Race Inc";
				case 0x14C7: return "Modular Technology Holdings Ltd";
				case 0x14C8: return "Turbocomm Tech. Inc.";
				case 0x14C9: return "ODIN Telesystems Inc";
				case 0x14CA: return "PE Logic Corp.";
				case 0x14CB: return "Billionton Systems Inc";
				case 0x14CC: return "NAKAYO Telecommunications Inc";
				case 0x14CD: return "Universal Scientific Ind.";
				case 0x14CE: return "Whistle Communications";
				case 0x14CF: return "TEK Microsystems Inc.";
				case 0x14D0: return "Ericsson Axe R & D";
				case 0x14D1: return "Computer Hi-Tech Co Ltd";
				case 0x14D2: return "Titan Electronics Inc";
				case 0x14D3: return "CIRTECH (UK) Ltd";
				case 0x14D4: return "Panacom Technology Corp";
				case 0x14D5: return "Nitsuko Corporation";
				case 0x14D6: return "Accusys Inc";
				case 0x14D7: return "Hirakawa Hewtech Corp";
				case 0x14D8: return "HOPF Elektronik GmBH";
				case 0x14D9: return "Alliance Semiconductor Corporation";
				case 0x14DA: return "National Aerospace Laboratories";
				case 0x14DB: return "AFAVLAB Technology Inc";
				case 0x14DC: return "Amplicon Liveline Ltd";
				case 0x14DD: return "Boulder Design Labs Inc";
				case 0x14DE: return "Applied Integration Corporation";
				case 0x14DF: return "ASIC Communications Corp";
				case 0x14E1: return "INVERTEX";
				case 0x14E2: return "INFOLIBRIA";
				case 0x14E3: return "AMTELCO";
				case 0x14E4: return "Broadcom Corporation";
				case 0x14E5: return "Pixelfusion Ltd";
				case 0x14E6: return "SHINING Technology Inc";
				case 0x14E7: return "3CX";
				case 0x14E8: return "RAYCER Inc";
				case 0x14E9: return "GARNETS System CO Ltd";
				case 0x14EA: return "Planex Communications, Inc";
				case 0x14EB: return "SEIKO EPSON Corp";
				case 0x14EC: return "ACQIRIS";
				case 0x14ED: return "DATAKINETICS Ltd";
				case 0x14EE: return "MASPRO KENKOH Corp";
				case 0x14EF: return "CARRY Computer ENG. CO Ltd";
				case 0x14F0: return "CANON RESEACH CENTRE FRANCE";
				case 0x14F1: return "Conexant Systems, Inc.";
				case 0x14F2: return "MOBILITY Electronics";
				case 0x14F3: return "BroadLogic";
				case 0x14F4: return "TOKYO Electronic Industry CO Ltd";
				case 0x14F5: return "SOPAC Ltd";
				case 0x14F6: return "COYOTE Technologies LLC";
				case 0x14F7: return "WOLF Technology Inc";
				case 0x14F8: return "AUDIOCODES Inc";
				case 0x14F9: return "AG COMMUNICATIONS";
				case 0x14FA: return "WANDEL & GOLTERMANN";
				case 0x14FB: return "TRANSAS MARINE (UK) Ltd";
				case 0x14FC: return "Quadrics Ltd";
				case 0x14FD: return "JAPAN Computer Industry Inc";
				case 0x14FE: return "ARCHTEK TELECOM Corp";
				case 0x14FF: return "TWINHEAD INTERNATIONAL Corp";
				case 0x1500: return "DELTA Electronics, Inc";
				case 0x1501: return "BANKSOFT CANADA Ltd";
				case 0x1502: return "MITSUBISHI ELECTRIC LOGISTICS SUPPORT Co Ltd";
				case 0x1503: return "KAWASAKI LSI USA Inc";
				case 0x1504: return "KAISER Electronics";
				case 0x1505: return "ITA INGENIEURBURO FUR TESTAUFGABEN GmbH";
				case 0x1506: return "CHAMELEON Systems Inc";
				case 0x1507: return "Motorola ?? / HTEC";
				case 0x1508: return "HONDA CONNECTORS/MHOTRONICS Inc";
				case 0x1509: return "FIRST INTERNATIONAL Computer Inc";
				case 0x150A: return "FORVUS RESEARCH Inc";
				case 0x150B: return "YAMASHITA Systems Corp";
				case 0x150C: return "KYOPAL CO Ltd";
				case 0x150D: return "WARPSPPED Inc";
				case 0x150E: return "C-PORT Corp";
				case 0x150F: return "INTEC GmbH";
				case 0x1510: return "BEHAVIOR TECH Computer Corp";
				case 0x1511: return "CENTILLIUM Technology Corp";
				case 0x1512: return "ROSUN Technologies Inc";
				case 0x1513: return "Raychem";
				case 0x1514: return "TFL LAN Inc";
				case 0x1515: return "Advent design";
				case 0x1516: return "MYSON Technology Inc";
				case 0x1517: return "ECHOTEK Corp";
				case 0x1518: return "Kontron Modular Computers GmbH";
				case 0x1519: return "TELEFON AKTIEBOLAGET LM Ericsson";
				case 0x151A: return "Globetek";
				case 0x151B: return "COMBOX Ltd";
				case 0x151C: return "DIGITAL AUDIO LABS Inc";
				case 0x151D: return "Fujitsu Computer Products Of America";
				case 0x151E: return "MATRIX Corp";
				case 0x151F: return "TOPIC SEMICONDUCTOR Corp";
				case 0x1520: return "CHAPLET System Inc";
				case 0x1521: return "BELL Corp";
				case 0x1522: return "MainPine Ltd";
				case 0x1523: return "MUSIC Semiconductors";
				case 0x1524: return "ENE Technology Inc";
				case 0x1525: return "IMPACT Technologies";
				case 0x1526: return "ISS, Inc";
				case 0x1527: return "SOLECTRON";
				case 0x1528: return "ACKSYS";
				case 0x1529: return "AMERICAN MICROSystems Inc";
				case 0x152A: return "QUICKTURN DESIGN Systems";
				case 0x152B: return "FLYTECH Technology CO Ltd";
				case 0x152C: return "MACRAIGOR Systems LLC";
				case 0x152D: return "QUANTA Computer Inc";
				case 0x152E: return "MELEC Inc";
				case 0x152F: return "PHILIPS - CRYPTO";
				case 0x1530: return "ACQIS Technology Inc";
				case 0x1531: return "CHRYON Corp";
				case 0x1532: return "ECHELON Corp";
				case 0x1533: return "BALTIMORE";
				case 0x1534: return "ROAD Corp";
				case 0x1535: return "EVERGREEN Technologies Inc";
				case 0x1536: return "ACTIS Computer";
				case 0x1537: return "DATALEX COMMUNCATIONS";
				case 0x1538: return "ARALION Inc";
				case 0x1539: return "ATELIER INFORMATIQUES et ELECTRONIQUE ETUDES S.A.";
				case 0x153A: return "ONO SOKKI";
				case 0x153B: return "TERRATEC Electronic GmbH";
				case 0x153C: return "ANTAL Electronic";
				case 0x153D: return "FILANET Corp";
				case 0x153E: return "TECHWELL Inc";
				case 0x153F: return "MIPS Technologies, Inc.";
				case 0x1540: return "PROVIDEO MULTIMEDIA Co Ltd";
				case 0x1541: return "MACHONE Communications";
				case 0x1542: return "Concurrent Computer Corporation";
				case 0x1543: return "SILICON Laboratories";
				case 0x1544: return "DCM DATA Systems";
				case 0x1545: return "VISIONTEK";
				case 0x1546: return "IOI Technology Corp";
				case 0x1547: return "MITUTOYO Corp";
				case 0x1548: return "JET PROPULSION Laboratory";
				case 0x1549: return "INTERCONNECT Systems Solutions";
				case 0x154A: return "MAX Technologies Inc";
				case 0x154B: return "COMPUTEX Co Ltd";
				case 0x154C: return "VISUAL Technology Inc";
				case 0x154D: return "PAN INTERNATIONAL Industrial Corp";
				case 0x154E: return "SERVOTEST Ltd";
				case 0x154F: return "STRATABEAM Technology";
				case 0x1550: return "OPEN NETWORK Co Ltd";
				case 0x1551: return "SMART Electronic DEVELOPMENT GmBH";
				case 0x1552: return "RACAL AIRTECH Ltd";
				case 0x1553: return "CHICONY Electronics Co Ltd";
				case 0x1554: return "PROLINK Microsystems Corp";
				case 0x1555: return "GESYTEC GmBH";
				case 0x1556: return "PLD APPLICATIONS";
				case 0x1557: return "MEDIASTAR Co Ltd";
				case 0x1558: return "CLEVO/KAPOK Computer";
				case 0x1559: return "SI LOGIC Ltd";
				case 0x155A: return "INNOMEDIA Inc";
				case 0x155B: return "PROTAC INTERNATIONAL Corp";
				case 0x155C: return "Cemax-Icon Inc";
				case 0x155D: return "Mac System Co Ltd";
				case 0x155E: return "LP Elektronik GmbH";
				case 0x155F: return "Perle Systems Ltd";
				case 0x1560: return "Terayon Communications Systems";
				case 0x1561: return "Viewgraphics Inc";
				case 0x1562: return "Symbol Technologies";
				case 0x1563: return "A-Trend Technology Co Ltd";
				case 0x1564: return "Yamakatsu Electronics Industry Co Ltd";
				case 0x1565: return "Biostar Microtech Int'l Corp";
				case 0x1566: return "Ardent Technologies Inc";
				case 0x1567: return "Jungsoft";
				case 0x1568: return "DDK Electronics Inc";
				case 0x1569: return "Palit Microsystems Inc.";
				case 0x156A: return "Avtec Systems";
				case 0x156B: return "2wire Inc";
				case 0x156C: return "Vidac Electronics GmbH";
				case 0x156D: return "Alpha-Top Corp";
				case 0x156E: return "Alfa Inc";
				case 0x156F: return "M-Systems Flash Disk Pioneers Ltd";
				case 0x1570: return "Lecroy Corp";
				case 0x1571: return "Contemporary Controls";
				case 0x1572: return "Otis Elevator Company";
				case 0x1573: return "Lattice - Vantis";
				case 0x1574: return "Fairchild Semiconductor";
				case 0x1575: return "Voltaire Advanced Data Security Ltd";
				case 0x1576: return "Viewcast COM";
				case 0x1578: return "HITT";
				case 0x1579: return "Dual Technology Corp";
				case 0x157A: return "Japan Elecronics Ind Inc";
				case 0x157B: return "Star Multimedia Corp";
				case 0x157C: return "Eurosoft (UK)";
				case 0x157D: return "Gemflex Networks";
				case 0x157E: return "Transition Networks";
				case 0x157F: return "PX Instruments Technology Ltd";
				case 0x1580: return "Primex Aerospace Co";
				case 0x1581: return "SEH Computertechnik GmbH";
				case 0x1582: return "Cytec Corp";
				case 0x1583: return "Inet Technologies Inc";
				case 0x1584: return "Uniwill Computer Corp";
				case 0x1585: return "Logitron";
				case 0x1586: return "Lancast Inc";
				case 0x1587: return "Konica Corp";
				case 0x1588: return "Solidum Systems Corp";
				case 0x1589: return "Atlantek Microsystems Pty Ltd";
				case 0x158A: return "Digalog Systems Inc";
				case 0x158B: return "Allied Data Technologies";
				case 0x158C: return "Hitachi Semiconductor & Devices Sales Co Ltd";
				case 0x158D: return "Point Multimedia Systems";
				case 0x158E: return "Lara Technology Inc";
				case 0x158F: return "Ditect Coop";
				case 0x1590: return "3PAR Inc.";
				case 0x1591: return "ARN";
				case 0x1592: return "Syba Tech Ltd";
				case 0x1593: return "Bops Inc";
				case 0x1594: return "Netgame Ltd";
				case 0x1595: return "Diva Systems Corp";
				case 0x1596: return "Folsom Research Inc";
				case 0x1597: return "Memec Design Services";
				case 0x1598: return "Granite Microsystems";
				case 0x1599: return "Delta Electronics Inc";
				case 0x159A: return "General Instrument";
				case 0x159B: return "Faraday Technology Corp";
				case 0x159C: return "Stratus Computer Systems";
				case 0x159D: return "Ningbo Harrison Electronics Co Ltd";
				case 0x159E: return "A-Max Technology Co Ltd";
				case 0x159F: return "Galea Network Security";
				case 0x15A0: return "Compumaster SRL";
				case 0x15A1: return "Geocast Network Systems";
				case 0x15A2: return "Catalyst Enterprises Inc";
				case 0x15A3: return "Italtel";
				case 0x15A4: return "X-Net OY";
				case 0x15A5: return "Toyota Macs Inc";
				case 0x15A6: return "Sunlight Ultrasound Technologies Ltd";
				case 0x15A7: return "SSE Telecom Inc";
				case 0x15A8: return "Shanghai Communications Technologies Center";
				case 0x15AA: return "Moreton Bay";
				case 0x15AB: return "Bluesteel Networks Inc";
				case 0x15AC: return "North Atlantic Instruments";
				case 0x15AD: return "VMware Inc";
				case 0x15AE: return "Amersham Pharmacia Biotech";
				case 0x15B0: return "Zoltrix International Ltd";
				case 0x15B1: return "Source Technology Inc";
				case 0x15B2: return "Mosaid Technologies Inc";
				case 0x15B3: return "Mellanox Technologies";
				case 0x15B4: return "CCI/TRIAD";
				case 0x15B5: return "Cimetrics Inc";
				case 0x15B6: return "Texas Memory Systems Inc";
				case 0x15B7: return "Sandisk Corp";
				case 0x15B8: return "ADDI-DATA GmbH";
				case 0x15B9: return "Maestro Digital Communications";
				case 0x15BA: return "Impacct Technology Corp";
				case 0x15BB: return "Portwell Inc";
				case 0x15BC: return "Agilent Technologies";
				case 0x15BD: return "DFI Inc";
				case 0x15BE: return "Sola Electronics";
				case 0x15BF: return "High Tech Computer Corp (HTC)";
				case 0x15C0: return "BVM Ltd";
				case 0x15C1: return "Quantel";
				case 0x15C2: return "Newer Technology Inc";
				case 0x15C3: return "Taiwan Mycomp Co Ltd";
				case 0x15C4: return "EVSX Inc";
				case 0x15C5: return "Procomp Informatics Ltd";
				case 0x15C6: return "Technical University of Budapest";
				case 0x15C7: return "Tateyama System Laboratory Co Ltd";
				case 0x15C8: return "Penta Media Co Ltd";
				case 0x15C9: return "Serome Technology Inc";
				case 0x15CA: return "Bitboys OY";
				case 0x15CB: return "AG Electronics Ltd";
				case 0x15CC: return "Hotrail Inc";
				case 0x15CD: return "Dreamtech Co Ltd";
				case 0x15CE: return "Genrad Inc";
				case 0x15CF: return "Hilscher GmbH";
				case 0x15D1: return "Infineon Technologies AG";
				case 0x15D2: return "FIC (First International Computer Inc)";
				case 0x15D3: return "NDS Technologies Israel Ltd";
				case 0x15D4: return "Iwill Corp";
				case 0x15D5: return "Tatung Co";
				case 0x15D6: return "Entridia Corp";
				case 0x15D7: return "Rockwell-Collins Inc";
				case 0x15D8: return "Cybernetics Technology Co Ltd";
				case 0x15D9: return "Super Micro Computer Inc";
				case 0x15DA: return "Cyberfirm Inc";
				case 0x15DB: return "Applied Computing Systems Inc";
				case 0x15DC: return "Litronic Inc";
				case 0x15DD: return "Sigmatel Inc";
				case 0x15DE: return "Malleable Technologies Inc";
				case 0x15DF: return "Infinilink Corp";
				case 0x15E0: return "Cacheflow Inc";
				case 0x15E1: return "Voice Technologies Group Inc";
				case 0x15E2: return "Quicknet Technologies Inc";
				case 0x15E3: return "Networth Technologies Inc";
				case 0x15E4: return "VSN Systemen BV";
				case 0x15E5: return "Valley technologies Inc";
				case 0x15E6: return "Agere Inc";
				case 0x15E7: return "Get Engineering Corp";
				case 0x15E8: return "National Datacomm Corp";
				case 0x15E9: return "Pacific Digital Corp";
				case 0x15EA: return "Tokyo Denshi Sekei K.K.";
				case 0x15EB: return "DResearch Digital Media Systems GmbH";
				case 0x15EC: return "Beckhoff GmbH";
				case 0x15ED: return "Macrolink Inc";
				case 0x15EE: return "In Win Development Inc";
				case 0x15EF: return "Intelligent Paradigm Inc";
				case 0x15F0: return "B-Tree Systems Inc";
				case 0x15F1: return "Times N Systems Inc";
				case 0x15F2: return "Diagnostic Instruments Inc";
				case 0x15F3: return "Digitmedia Corp";
				case 0x15F4: return "Valuesoft";
				case 0x15F5: return "Power Micro Research";
				case 0x15F6: return "Extreme Packet Device Inc";
				case 0x15F7: return "Banctec";
				case 0x15F8: return "Koga Electronics Co";
				case 0x15F9: return "Zenith Electronics Corp";
				case 0x15FA: return "J.P. Axzam Corp";
				case 0x15FB: return "Zilog Inc";
				case 0x15FC: return "Techsan Electronics Co Ltd";
				case 0x15FD: return "N-CUBED.NET";
				case 0x15FE: return "Kinpo Electronics Inc";
				case 0x15FF: return "Fastpoint Technologies Inc";
				case 0x1600: return "Northrop Grumman - Canada Ltd";
				case 0x1601: return "Tenta Technology";
				case 0x1602: return "Prosys-tec Inc";
				case 0x1603: return "Nokia Wireless Communications";
				case 0x1604: return "Central System Research Co Ltd";
				case 0x1605: return "Pairgain Technologies";
				case 0x1606: return "Europop AG";
				case 0x1607: return "Lava Semiconductor Manufacturing Inc";
				case 0x1608: return "Automated Wagering International";
				case 0x1609: return "Scimetric Instruments Inc";
				case 0x1612: return "Telesynergy Research Inc.";
				case 0x1619: return "FarSite Communications Ltd";
				case 0x161F: return "Rioworks";
				case 0x1626: return "TDK Semiconductor Corp.";
				case 0x1629: return "Kongsberg Spacetec AS";
				case 0x1631: return "Packard Bell B.V.";
				case 0x1637: return "Linksys";
				case 0x1638: return "Standard Microsystems Corp [SMC]";
				case 0x163C: return "Smart Link Ltd.";
				case 0x1641: return "MKNet Corp.";
				case 0x1657: return "Brocade Communications Systems, Inc.";
				case 0x165A: return "Epix Inc";
				case 0x165D: return "Hsing Tech. Enterprise Co., Ltd.";
				case 0x165F: return "Linux Media Labs, LLC";
				case 0x1661: return "Worldspace Corp.";
				case 0x1668: return "Actiontec Electronics Inc";
				case 0x166D: return "Broadcom Corporation";
				case 0x1677: return "Bernecker + Rainer";
				case 0x1678: return "NetEffect";
				case 0x1679: return "Tokyo Electron Device Ltd.";
				case 0x167B: return "ZyDAS Technology Corp.";
				case 0x167D: return "Samsung Electro-Mechanics Co., Ltd.";
				case 0x167E: return "ONNTO Corp.";
				case 0x1681: return "Hercules";
				case 0x1682: return "XFX Pine Group Inc.";
				case 0x1688: return "CastleNet Technology Inc.";
				case 0x168C: return "Atheros Communications Inc.";
				case 0x1695: return "EPoX Computer Co., Ltd.";
				case 0x169C: return "Netcell Corporation";
				case 0x169D: return "Club-3D VB (Wrong ID)";
				case 0x16A5: return "Tekram Technology Co.,Ltd.";
				case 0x16AB: return "Global Sun Technology Inc";
				case 0x16AE: return "SafeNet Inc";
				case 0x16AF: return "SparkLAN Communications, Inc.";
				case 0x16B4: return "Aspex Semiconductor Ltd";
				case 0x16B8: return "Sonnet Technologies, Inc.";
				case 0x16BE: return "Creatix Polymedia GmbH";
				case 0x16C6: return "Micrel-Kendin";
				case 0x16C8: return "Octasic Inc.";
				case 0x16C9: return "EONIC B.V. The Netherlands";
				case 0x16CA: return "CENATEK Inc";
				case 0x16CD: return "Densitron Technologies";
				case 0x16CE: return "Roland Corp.";
				case 0x16D5: return "Acromag, Inc.";
				case 0x16DA: return "Advantech Co., Ltd.";
				case 0x16DF: return "PIKA Technologies Inc.";
				case 0x16E3: return "European Space Agency";
				case 0x16E5: return "Intellon Corp.";
				case 0x16EC: return "U.S. Robotics";
				case 0x16ED: return "Sycron N. V.";
				case 0x16F3: return "Jetway Information Co., Ltd.";
				case 0x16F4: return "Vweb Corp";
				case 0x16F6: return "VideoTele.com, Inc.";
				case 0x1702: return "Internet Machines Corporation (IMC)";
				case 0x1705: return "Digital First, Inc.";
				case 0x170B: return "NetOctave";
				case 0x170C: return "YottaYotta Inc.";
				case 0x1719: return "EZChip Technologies";
				case 0x1725: return "Vitesse Semiconductor";
				case 0x172A: return "Accelerated Encryption";
				case 0x1734: return "Fujitsu Siemens Computers";
				case 0x1735: return "Aten International Co. Ltd.";
				case 0x1737: return "Linksys";
				case 0x173B: return "Altima (nee Broadcom)";
				case 0x1743: return "Peppercon AG";
				case 0x1745: return "ViXS Systems, Inc.";
				case 0x1749: return "RLX Technologies";
				case 0x174B: return "PC Partner Limited";
				case 0x174D: return "WellX Telecom SA";
				case 0x175C: return "AudioScience Inc";
				case 0x175E: return "Sanera Systems, Inc.";
				case 0x1760: return "TEDIA spol. s r. o.";
				case 0x1771: return "InnoVISION Multimedia Ltd.";
				case 0x1775: return "SBS Technologies";
				case 0x177D: return "Cavium Networks";
				case 0x1787: return "Hightech Information System Ltd.";
				case 0x1789: return "Ennyah Technologies Corp.";
				case 0x1796: return "Research Centre Juelich";
				case 0x1797: return "Techwell Inc.";
				case 0x1799: return "Belkin";
				case 0x179A: return "id Quantique";
				case 0x179C: return "Data Patterns";
				case 0x17A0: return "Genesys Logic, Inc";
				case 0x17AA: return "Lenovo";
				case 0x17AB: return "Phillips Components";
				case 0x17AF: return "Hightech Information System Ltd.";
				case 0x17B3: return "Hawking Technologies";
				case 0x17B4: return "Indra Networks, Inc.";
				case 0x17C0: return "Wistron Corp.";
				case 0x17C2: return "Newisys, Inc.";
				case 0x17CB: return "Airgo Networks Inc";
				case 0x17CC: return "NetChip Technology, Inc";
				case 0x17CF: return "Z-Com, Inc.";
				case 0x17D3: return "Areca Technology Corp.";
				case 0x17D5: return "S2io Inc.";
				case 0x17DB: return "Cray Inc";
				case 0x17DE: return "KWorld Computer Co. Ltd.";
				case 0x17E4: return "Sectra AB";
				case 0x17E6: return "Entropic Communications Inc.";
				case 0x17EE: return "Connect Components Ltd";
				case 0x17F2: return "Albatron Corp.";
				case 0x17F3: return "RDC Semiconductor, Inc.";
				case 0x17F7: return "Topdek Semiconductor Inc.";
				case 0x17FE: return "Linksys, A Division of Cisco Systems";
				case 0x17FF: return "Benq Corporation";
				case 0x1803: return "ProdaSafe GmbH";
				case 0x1805: return "Euresys S.A.";
				case 0x1809: return "Lumanate, Inc.";
				case 0x1813: return "Ambient Technologies Inc";
				case 0x1814: return "RaLink";
				case 0x1815: return "Devolo AG";
				case 0x1820: return "InfiniCon Systems Inc.";
				case 0x1822: return "Twinhan Technology Co. Ltd";
				case 0x182D: return "SiteCom Europe BV";
				case 0x182E: return "Raza Microelectronics, Inc.";
				case 0x182F: return "Broadcom";
				case 0x1830: return "Credence Systems Corporation";
				case 0x183B: return "MikroM GmbH";
				case 0x1849: return "ASRock Incorporation";
				case 0x184A: return "Thales Computers";
				case 0x1851: return "Microtune, Inc.";
				case 0x1852: return "Anritsu Corp.";
				case 0x1853: return "SMSC Automotive Infotainment System Group";
				case 0x1854: return "LG Electronics, Inc.";
				case 0x185B: return "Compro Technology, Inc.";
				case 0x185F: return "Wistron NeWeb Corp.";
				case 0x1864: return "SilverBack";
				case 0x1867: return "Topspin Communications";
				case 0x186C: return "Humusoft, s.r.o.";
				case 0x186F: return "WiNRADiO Communications";
				case 0x1876: return "L-3 Communications";
				case 0x187E: return "ZyXEL Communication Corporation";
				case 0x1885: return "Avvida Systems Inc.";
				case 0x1888: return "Varisys Ltd";
				case 0x188A: return "Ample Communications, Inc";
				case 0x1890: return "Egenera, Inc.";
				case 0x1894: return "KNC One";
				case 0x1896: return "B&B Electronics Manufacturing Company, Inc.";
				case 0x1897: return "AMtek";
				case 0x18A1: return "Astute Networks Inc.";
				case 0x18A3: return "AT&T";
				case 0x18AC: return "DViCO Corporation";
				case 0x18B8: return "Ammasso";
				case 0x18BC: return "Info-Tek Corp.";
				case 0x18C3: return "Micronas Semiconductor Holding AG";
				case 0x18C8: return "Cray Inc";
				case 0x18C9: return "ARVOO Engineering BV";
				case 0x18CA: return "XGI Technology Inc. (eXtreme Graphics Innovation)";
				case 0x18D2: return "Sitecom";
				case 0x18D8: return "Dialogue Technology Corp.";
				case 0x18DD: return "Artimi Inc";
				case 0x18E6: return "MPL AG";
				case 0x18EB: return "Advance Multimedia Internet Technology, Inc.";
				case 0x18EC: return "Cesnet, z.s.p.o.";
				case 0x18EE: return "Chenming Mold Ind. Corp.";
				case 0x18F1: return "Spectrum GmbH";
				case 0x18F6: return "NextIO";
				case 0x18F7: return "Commtech, Inc.";
				case 0x18FB: return "Resilience Corporation";
				case 0x1904: return "Hangzhou Silan Microelectronics Co., Ltd.";
				case 0x1905: return "Micronas USA, Inc.";
				case 0x1912: return "Renesas Technology Corp.";
				case 0x1919: return "Soltek Computer Inc.";
				case 0x1923: return "Sangoma Technologies Corp.";
				case 0x1924: return "Solarflare Communications";
				case 0x192E: return "TransDimension";
				case 0x1931: return "Option N.V.";
				case 0x1932: return "DiBcom";
				case 0x193C: return "MAXIM Integrated Products";
				case 0x193F: return "Comtech AHA Corp.";
				case 0x1942: return "ClearSpeed Technology plc";
				case 0x194A: return "DapTechnology B.V.";
				case 0x1954: return "Curtis, Inc.";
				case 0x1957: return "Freescale Semiconductor Inc";
				case 0x1958: return "Faster Technology, LLC.";
				case 0x1959: return "PA Semi, Inc";
				case 0x1966: return "Orad Hi-Tec Systems";
				case 0x1969: return "Attansic Technology Corp.";
				case 0x196A: return "Sensory Networks Inc.";
				case 0x196D: return "Club-3D BV";
				case 0x1971: return "AGEIA Technologies, Inc.";
				case 0x1974: return "TransferZentrum Mikroelektronik";
				case 0x1977: return "Parsec";
				case 0x197B: return "JMicron Technologies, Inc.";
				case 0x1982: return "Distant Early Warning Communications Inc";
				case 0x1989: return "Montilio Inc.";
				case 0x198A: return "Nallatech Ltd.";
				case 0x1993: return "Innominate Security Technologies AG";
				case 0x199A: return "Pulse-LINK, Inc.";
				case 0x19A2: return "ServerEngines Corp.";
				case 0x19A8: return "DAQDATA GmbH";
				case 0x19AC: return "Kasten Chase Applied Research";
				case 0x19AE: return "Progeny Systems Corporation";
				case 0x19C1: return "Exegy Inc.";
				case 0x19D1: return "Motorola Expedience";
				case 0x19D4: return "Quixant Limited";
				case 0x19DA: return "ZOTAC International (MCO) Ltd.";
				case 0x19DE: return "Pico Computing";
				case 0x19E2: return "Vector Informatik GmbH";
				case 0x19E3: return "DDRdrive LLC";
				case 0x19E7: return "NET (Network Equipment Technologies)";
				case 0x19EE: return "Netronome Systems, Inc.";
				case 0x1A03: return "ASPEED Technology, Inc.";
				case 0x1A07: return "Kvaser AB";
				case 0x1A08: return "Sierra semiconductor";
				case 0x1A0E: return "DekTec Digital Video B.V.";
				case 0x1A17: return "Force10 Networks, Inc.";
				case 0x1A1D: return "GFaI e.V.";
				case 0x1A1E: return "3Leaf Systems, Inc.";
				case 0x1A22: return "Ambric Inc.";
				case 0x1A29: return "Fortinet, Inc.";
				case 0x1A2B: return "Ascom AG";
				case 0x1A51: return "Hectronic AB";
				case 0x1A56: return "Bigfoot Networks, Inc.";
				case 0x1A57: return "Highly Reliable Systems";
				case 0x1A58: return "Razer USA Ltd.";
				case 0x1A5D: return "Celoxica";
				case 0x1A5E: return "Aprius Inc.";
				case 0x1A5F: return "System TALKS Inc.";
				case 0x1A68: return "VirtenSys Limited";
				case 0x1A71: return "XenSource, Inc.";
				case 0x1A73: return "Violin Memory, Inc";
				case 0x1A76: return "Wavesat";
				case 0x1A77: return "Lightfleet Corporation";
				case 0x1A78: return "Virident Systems Inc.";
				case 0x1A84: return "Commex Technologies";
				case 0x1A8C: return "Verigy Pte. Ltd.";
				case 0x1A8E: return "DRS Technologies";
				case 0x1AA8: return "Ciprico, Inc.";
				case 0x1AAE: return "Global Velocity, Inc.";
				case 0x1AB6: return "CalDigit, Inc.";
				case 0x1AB9: return "Espia Srl";
				case 0x1ADE: return "Spin Master Ltd.";
				case 0x1AE0: return "Google, Inc.";
				case 0x1AE8: return "Silicon Software GmbH";
				case 0x1AEC: return "Wolfson Microelectronics";
				case 0x1AEE: return "Caustic Graphics Inc.";
				case 0x1AF4: return "Qumranet, Inc.";
				case 0x1AF5: return "Netezza Corp.";
				case 0x1AFA: return "J & W Electronics Co., Ltd.";
				case 0x1B13: return "Jaton Corp";
				case 0x1B36: return "Red Hat, Inc.";
				case 0x1B3E: return "Teradata Corp.";
				case 0x1B40: return "Schooner Information Technology, Inc.";
				case 0x1B55: return "NetUP Inc.";
				case 0x1C1C: return "Symphony";
				case 0x1D44: return "DPT";
				case 0x1DE1: return "Tekram Technology Co.,Ltd.";
				case 0x1FC0: return "Ascom (Finland) Oy";
				case 0x1FC1: return "QLogic, Corp.";
				case 0x1FC9: return "Tehuti Networks Ltd.";
				case 0x1FCE: return "Cognio Inc.";
				case 0x1FD4: return "SUNIX Co., Ltd.";
				case 0x2000: return "Smart Link Ltd.";
				case 0x2001: return "Temporal Research Ltd";
				case 0x2003: return "Smart Link Ltd.";
				case 0x2004: return "Smart Link Ltd.";
				case 0x2116: return "ZyDAS Technology Corp.";
				case 0x21C3: return "21st Century Computer Corp.";
				case 0x22B8: return "Motorola, Inc.";
				case 0x2304: return "Colorgraphic Communications Corp.";
				case 0x2348: return "Racore";
				case 0x2646: return "Kingston Technologies";
				case 0x270B: return "Xantel Corporation";
				case 0x270F: return "Chaintech Computer Co. Ltd";
				case 0x2711: return "AVID Technology Inc.";
				case 0x29B4: return "82q35 Express MEI Controller";
				case 0x2A15: return "3D Vision(???)";
				case 0x3000: return "Hansol Electronics Inc.";
				case 0x3142: return "Post Impression Systems.";
				case 0x3388: return "Hint Corp";
				case 0x3411: return "Quantum Designs (H.K.) Inc";
				case 0x3442: return "Bihl+Wiedemann GmbH";
				case 0x3475: return "Arastra Inc.";
				case 0x3513: return "ARCOM Control Systems Ltd";
				case 0x3842: return "eVga.com. Corp.";
				case 0x38EF: return "4Links";
				case 0x3D3D: return "3DLabs";
				case 0x4005: return "Avance Logic Inc.";
				case 0x4033: return "Addtron Technology Co, Inc.";
				case 0x4040: return "NetXen Incorporated";
				case 0x4143: return "Digital Equipment Corp";
				case 0x4144: return "Alpha Data";
				case 0x4150: return "ONA Electroerosion";
				case 0x415A: return "Auzentech, Inc.";
				case 0x416C: return "Aladdin Knowledge Systems";
				case 0x4321: return "Tata Power Strategic Electronics Division";
				case 0x434E: return "CAST Navigation LLC";
				case 0x4444: return "Internext Compression Inc";
				case 0x4468: return "Bridgeport machines";
				case 0x4594: return "Cogetec Informatique Inc";
				case 0x45FB: return "Baldor Electric Company";
				case 0x4680: return "Umax Computer Corp";
				case 0x4843: return "Hercules Computer Technology Inc";
				case 0x4916: return "RedCreek Communications Inc";
				case 0x4943: return "Growth Networks";
				case 0x494F: return "ACCES I/O Products, Inc.";
				case 0x4978: return "Axil Computer Inc";
				case 0x4A14: return "NetVin";
				case 0x4B10: return "Buslogic Inc.";
				case 0x4C48: return "LUNG HWA Electronics";
				case 0x4C53: return "SBS Technologies";
				case 0x4CA1: return "Seanix Technology Inc";
				case 0x4D51: return "MediaQ Inc.";
				case 0x4D54: return "Microtechnica Co Ltd";
				case 0x4D56: return "MATRIX VISION GmbH";
				case 0x4DDC: return "ILC Data Device Corp";
				case 0x5045: return "University of Toronto";
				case 0x5046: return "GemTek Technology Corporation";
				case 0x5053: return "Voyetra Technologies";
				case 0x50B2: return "TerraTec Electronic GmbH";
				case 0x5136: return "S S Technologies";
				case 0x5143: return "Qualcomm Inc";
				case 0x5145: return "Ensoniq (Old)";
				case 0x5168: return "Animation Technologies Inc.";
				case 0x5301: return "Alliance Semiconductor Corp.";
				case 0x5333: return "S3 Inc.";
				case 0x544C: return "Teralogic Inc";
				case 0x5455: return "Technische University Berlin";
				case 0x5456: return "GoTView";
				case 0x5519: return "Cnet Technologies, Inc.";
				case 0x5544: return "Dunord Technologies";
				case 0x5555: return "Genroco, Inc";
				case 0x5654: return "VoiceTronix Pty Ltd";
				case 0x5700: return "Netpower";
				case 0x584D: return "AuzenTech Co., Ltd.";
				case 0x5851: return "Exacq Technologies";
				case 0x5853: return "XenSource, Inc.";
				case 0x5ACE: return "Beholder International Ltd.";
				case 0x6356: return "UltraStor";
				case 0x6374: return "c't Magazin fuer Computertechnik";
				case 0x6409: return "Logitec Corp.";
				case 0x6549: return "Teradici Corp.";
				case 0x6666: return "Decision Computer International Co.";
				case 0x6900: return "Qumranet";
				case 0x7063: return "pcHDTV";
				case 0x7284: return "HT OMEGA Inc.";
				case 0x7604: return "O.N. Electronic Co Ltd.";
				case 0x7BDE: return "MIDAC Corporation";
				case 0x7FED: return "PowerTV";
				case 0x8008: return "Quancom Electronic GmbH";
				case 0x807D: return "Asustek Computer, Inc.";
				case 0x8086: return "Intel Corporation";
				case 0x80EE: return "InnoTek Systemberatung GmbH";
				case 0x8322: return "Sodick America Corp.";
				case 0x8384: return "SigmaTel";
				case 0x8401: return "TRENDware International Inc.";
				case 0x8686: return "ScaleMP";
				case 0x8800: return "Trigem Computer Inc.";
				case 0x8866: return "T-Square Design Inc.";
				case 0x8888: return "Silicon Magic";
				case 0x8912: return "TRX";
				case 0x8C4A: return "Winbond";
				case 0x8E0E: return "Computone Corporation";
				case 0x8E2E: return "KTI";
				case 0x9004: return "Adaptec";
				case 0x9005: return "Adaptec";
				case 0x907F: return "Atronics";
				case 0x919A: return "Gigapixel Corp";
				case 0x9412: return "Holtek";
				case 0x9699: return "Omni Media Technology Inc";
				case 0x9710: return "NetMos Technology";
				case 0x9902: return "Stargen Inc.";
				case 0xA0A0: return "AOPEN Inc.";
				case 0xA0F1: return "UNISYS Corporation";
				case 0xA200: return "NEC Corporation";
				case 0xA259: return "Hewlett Packard";
				case 0xA25B: return "Hewlett Packard GmbH PL24-MKT";
				case 0xA304: return "Sony";
				case 0xA727: return "3Com Corporation";
				case 0xAA42: return "Scitex Digital Video";
				case 0xAA55: return "Ncomputing X300 PCI-Engine";
				case 0xAAAA: return "Adnaco Technology Inc.";
				case 0xABCD: return "Vadatech Inc.";
				case 0xAC1E: return "Digital Receiver Technology Inc";
				case 0xAC3D: return "Actuality Systems";
				case 0xAD00: return "Alta Data Technologies LLC";
				case 0xAECB: return "Adrienne Electronics Corporation";
				case 0xAFFE: return "Sirrix AG security technologies";
				case 0xB10B: return "Uakron PCI Project";
				case 0xB1B3: return "Shiva Europe Limited";
				case 0xBD11: return "Pinnacle Systems, Inc. (Wrong ID)";
				case 0xBDBD: return "Blackmagic Design";
				case 0xC001: return "TSI Telsys";
				case 0xC0A9: return "Micron/Crucial Technology";
				case 0xC0DE: return "Motorola";
				case 0xC0FE: return "Motion Engineering, Inc.";
				case 0xCA50: return "Varian Australia Pty Ltd";
				case 0xCACE: return "CACE Technologies, Inc.";
				case 0xCAFE: return "Chrysalis-ITS";
				case 0xCCCC: return "Catapult Communications";
				case 0xCCEC: return "Curtiss-Wright Controls Embedded Computing";
				case 0xCDDD: return "Tyzx, Inc.";
				case 0xCEBA: return "KEBA AG";
				case 0xD161: return "Digium, Inc.";
				case 0xD4D4: return "Dy4 Systems Inc";
				case 0xD531: return "I+ME ACTIA GmbH";
				case 0xD84D: return "Exsys";
				case 0xDB10: return "Diablo Technologies";
				case 0xDEAD: return "Indigita Corporation";
				case 0xDEAF: return "Middle Digital Inc.";
				case 0xDEDA: return "SoftHard Technology Ltd.";
				case 0xE000: return "Winbond";
				case 0xE159: return "Tiger Jet Network Inc.";
				case 0xE4BF: return "EKF Elektronik GmbH";
				case 0xE55E: return "Essence Technology, Inc.";
				case 0xEA01: return "Eagle Technology";
				case 0xEA60: return "RME";
				case 0xEABB: return "Aashima Technology B.V.";
				case 0xEACE: return "Endace Measurement Systems, Ltd";
				case 0xEC80: return "Belkin Corporation";
				case 0xECC0: return "Echo Digital Audio Corporation";
				case 0xEDD8: return "ARK Logic Inc";
				case 0xF043: return "ASUSTeK Computer Inc. (Wrong ID)";
				case 0xF05B: return "Foxconn International, Inc. (Wrong ID)";
				case 0xF1D0: return "AJA Video";
				case 0xF5F5: return "F5 Networks, Inc.";
				case 0xF849: return "ASRock Incorporation (Wrong ID)";
				case 0xFA57: return "Interagon AS";
				case 0xFAB7: return "Fabric7 Systems, Inc.";
				case 0xFEBD: return "Ultraview Corp.";
				case 0xFEDA: return "Broadcom Inc";
				case 0xFEDE: return "Fedetec Inc.";
				case 0xFFFD: return "XenSource, Inc.";
				case 0xFFFE: return "VMWare Inc (temporary ID)";
				case 0xFFFF: return "Illegal Vendor ID";
				default: return string.Empty;
			}
		}

		/// <summary>
		/// Lookups the specified vendor ID.
		/// </summary>
		/// <param name="vendorID">The vendor ID.</param>
		/// <param name="deviceID">The device ID.</param>
		/// <returns></returns>
		public static string Lookup(ushort vendorID, ushort deviceID)
		{
			switch ((uint)(((uint)vendorID << 16) | (uint)deviceID))
			{
				
				default: return string.Empty;
			}
		}
		/// <summary>
		/// Lookups the specified vendor ID.
		/// </summary>
		/// <param name="vendorID">The vendor ID.</param>
		/// <param name="deviceID">The device ID.</param>
		/// <param name="subSystem">The sub system.</param>
		/// <param name="subVendor">The sub vendor.</param>
		/// <returns></returns>
		public static string Lookup(ushort vendorID, ushort deviceID, ushort subSystem, ushort subVendor)
		{
#if !__MonoCS__
			switch ((((ulong)vendorID << 48) | ((ulong)deviceID << 32) | ((ulong)subSystem << 16) | subVendor))
			{
				
				default: return string.Empty;
			}
#else
			return string.Empty;
#endif
		}
	}
}
