// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Compiler.Framework.Transform.Auto.StrengthReduction
{
	/// <summary>
	/// Compare64x32Add32UnsignedRange
	/// </summary>
	public sealed class Compare64x32Add32UnsignedRange : BaseTransformation
	{
		public Compare64x32Add32UnsignedRange() : base(IRInstruction.Compare64x32)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (context.ConditionCode != ConditionCode.Equal)
				return false;

			if (!context.Operand1.IsVirtualRegister)
				return false;

			if (context.Operand1.Definitions.Count != 1)
				return false;

			if (context.Operand1.Definitions[0].Instruction != IRInstruction.DivUnsigned32)
				return false;

			if (!IsResolvedConstant(context.Operand2))
				return false;

			if (!IsResolvedConstant(context.Operand1.Definitions[0].Operand2))
				return false;

			if (IsZero(context.Operand1.Definitions[0].Operand2))
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1.Definitions[0].Operand1;
			var t2 = context.Operand1.Definitions[0].Operand2;
			var t3 = context.Operand2;

			var v1 = transformContext.AllocateVirtualRegister(transformContext.I4);

			var e1 = transformContext.CreateConstant(MulUnsigned32(To32(t2), To32(t3)));

			context.SetInstruction(IRInstruction.Sub32, v1, t1, e1);
			context.AppendInstruction(IRInstruction.Compare64x32, ConditionCode.UnsignedLess, result, v1, t2);
		}
	}

	/// <summary>
	/// Compare64x32Add32UnsignedRange_v1
	/// </summary>
	public sealed class Compare64x32Add32UnsignedRange_v1 : BaseTransformation
	{
		public Compare64x32Add32UnsignedRange_v1() : base(IRInstruction.Compare64x32)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (context.ConditionCode != ConditionCode.Equal)
				return false;

			if (!context.Operand2.IsVirtualRegister)
				return false;

			if (context.Operand2.Definitions.Count != 1)
				return false;

			if (context.Operand2.Definitions[0].Instruction != IRInstruction.DivUnsigned32)
				return false;

			if (!IsResolvedConstant(context.Operand1))
				return false;

			if (!IsResolvedConstant(context.Operand2.Definitions[0].Operand2))
				return false;

			if (IsZero(context.Operand2.Definitions[0].Operand2))
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1;
			var t2 = context.Operand2.Definitions[0].Operand1;
			var t3 = context.Operand2.Definitions[0].Operand2;

			var v1 = transformContext.AllocateVirtualRegister(transformContext.I4);

			var e1 = transformContext.CreateConstant(MulUnsigned32(To32(t3), To32(t1)));

			context.SetInstruction(IRInstruction.Sub32, v1, t2, e1);
			context.AppendInstruction(IRInstruction.Compare64x32, ConditionCode.UnsignedLess, result, v1, t3);
		}
	}
}
