// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Compiler.Framework.Transform.Auto.Simplification
{
	/// <summary>
	/// RemSigned32By2
	/// </summary>
	public sealed class RemSigned32By2 : BaseTransformation
	{
		public RemSigned32By2() : base(IRInstruction.RemSigned32)
		{
		}

		public override bool Match(Context context, TransformContext transformContext)
		{
			if (!context.Operand2.IsResolvedConstant)
				return false;

			if (context.Operand2.ConstantUnsigned64 != 2)
				return false;

			return true;
		}

		public override void Transform(Context context, TransformContext transformContext)
		{
			var result = context.Result;

			var t1 = context.Operand1;

			var c1 = transformContext.CreateConstant(1);

			context.SetInstruction(IRInstruction.And32, result, t1, c1);
		}
	}
}
