// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CallVirtual
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.Instructions.BaseIRInstruction" />
public sealed class CallVirtual : BaseIRInstruction
{
	public CallVirtual()
		: base(0, 0)
	{
	}

	public override bool IsFlowNext => false;

	public override bool IsCall => true;

	public override bool HasVariableOperands => true;
}
