// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckedConversionR8ToU16
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.Instructions.BaseIRInstruction" />
public sealed class CheckedConversionR8ToU16 : BaseIRInstruction
{
	public CheckedConversionR8ToU16()
		: base(1, 1)
	{
	}
}
