// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckedConversionR8ToI32
/// </summary>
public sealed class CheckedConversionR8ToI32 : BaseIRInstruction
{
	public CheckedConversionR8ToI32()
		: base(1, 1)
	{
	}
}
