// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckedConversionI32ToU8
/// </summary>
public sealed class CheckedConversionI32ToU8 : BaseIRInstruction
{
	public CheckedConversionI32ToU8()
		: base(1, 1)
	{
	}
}
