// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckedConversionR8ToI64
/// </summary>
public sealed class CheckedConversionR8ToI64 : BaseIRInstruction
{
	public CheckedConversionR8ToI64()
		: base(1, 1)
	{
	}
}
