// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CheckedConversionI64ToI8
/// </summary>
public sealed class CheckedConversionI64ToI8 : BaseIRInstruction
{
	public CheckedConversionI64ToI8()
		: base(1, 1)
	{
	}
}
