// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.MosaTypeSystem;

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// CompareObject
/// </summary>
public sealed class CompareObject : BaseIRInstruction
{
	public CompareObject()
		: base(2, 1)
	{
	}

	public override bool IsCompare => true;
}
