// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ConvertR4ToI32
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.Instructions.BaseIRInstruction" />
public sealed class ConvertR4ToI32 : BaseIRInstruction
{
	public ConvertR4ToI32()
		: base(1, 1)
	{
	}
}
