// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// LoadR8
/// </summary>
public sealed class LoadR8 : BaseIRInstruction
{
	public LoadR8()
		: base(2, 1)
	{
	}

	public override bool IsMemoryRead => true;
}
