// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Neg32
/// </summary>
public sealed class Neg32 : BaseIRInstruction
{
	public Neg32()
		: base(2, 1)
	{
	}

	public override bool IsCommutative => true;
}
