// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// PhiObject
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.Instructions.BaseIRInstruction" />
public sealed class PhiObject : BaseIRInstruction
{
	public PhiObject()
		: base(0, 0)
	{
	}

	public override bool IsPhi => true;

	public override bool HasVariableOperands => true;
}
