// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ShiftLeft32
/// </summary>
/// <seealso cref="Mosa.Compiler.Framework.Instructions.BaseIRInstruction" />
public sealed class ShiftLeft32 : BaseIRInstruction
{
	public ShiftLeft32()
		: base(2, 1)
	{
	}
}
