// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// SignExtend16x32
/// </summary>
public sealed class SignExtend16x32 : BaseIRInstruction
{
	public SignExtend16x32()
		: base(1, 1)
	{
	}
}
