// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// ThrowOverflow
/// </summary>
public sealed class ThrowOverflow : BaseIRInstruction
{
	public ThrowOverflow()
		: base(0, 0)
	{
	}
}
