// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

namespace Mosa.Compiler.Framework.Instructions;

/// <summary>
/// Truncate64x32
/// </summary>
public sealed class Truncate64x32 : BaseIRInstruction
{
	public Truncate64x32()
		: base(1, 1)
	{
	}
}
