/*
 * (c) 2010 MOSA - The Managed Operating System Alliance
 *
 * Licensed under the terms of the New BSD License.
 *
 * Authors:
 *  Phil Garcia (tgiphil) <phil@thinkedge.com>
 */

/* DO NOT MODIFY THIS FILE COMPUTER GENERATED CODE. */

using System;

using MbUnit.Framework;

namespace Test.Mosa.Runtime.CompilerFramework.CLI
{
	public partial class SByteFixture
	{
		#region Add
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void AddSbyteSbyte(sbyte a, sbyte b)
		{
			this.arithmeticTests.Add((a + b), a, b);
		}
		
		#endregion // Add
		
		#region Sub
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void SubSbyteSbyte(sbyte a, sbyte b)
		{
			this.arithmeticTests.Sub((a - b), a, b);
		}
		
		#endregion // Sub
		
		#region Mul
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void MulSbyteSbyte(sbyte a, sbyte b)
		{
			this.arithmeticTests.Mul((a * b), a, b);
		}
		
		#endregion // Mul
		
		#region Div
		
		[Row(0, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void DivSbyteSbyte(sbyte a, sbyte b)
		{
			this.arithmeticTests.Div((a / b), a, b);
		}
		
		#endregion // Div
		
		#region Rem
		
		[Row(0, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(0, 1)]
		//[Row(0, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(0, sbyte.MaxValue)]
		//[Row(0, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(0, sbyte.MaxValue - 1)]
		//[Row(0, -1, ExpectedException = typeof(OverflowException))]
		//[Row(0, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Row(1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(1, 1)]
		//[Row(1, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(1, sbyte.MaxValue)]
		//[Row(1, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(1, sbyte.MaxValue - 1)]
		//[Row(1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(1, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue, 1)]
		//[Row(sbyte.MinValue, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		//[Row(sbyte.MinValue, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		//[Row(sbyte.MinValue, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue, 1)]
		//[Row(sbyte.MaxValue, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		//[Row(sbyte.MaxValue, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		//[Row(sbyte.MaxValue, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 1, 1)]
		//[Row(sbyte.MinValue + 1, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		//[Row(sbyte.MinValue + 1, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		//[Row(sbyte.MinValue + 1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 1, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue - 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue - 1, 1)]
		//[Row(sbyte.MaxValue - 1, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		//[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		//[Row(sbyte.MaxValue - 1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Row(-1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-1, 1)]
		//[Row(-1, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(-1, sbyte.MaxValue)]
		//[Row(-1, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(-1, sbyte.MaxValue - 1)]
		//[Row(-1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(-1, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 2, 1)]
		//[Row(sbyte.MinValue + 2, sbyte.MinValue, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		//[Row(sbyte.MinValue + 2, sbyte.MinValue + 1, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		//[Row(sbyte.MinValue + 2, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 2, sbyte.MinValue + 2, ExpectedException = typeof(OverflowException))]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void RemSbyteSbyte(sbyte a, sbyte b)
		{
			this.arithmeticTests.Rem((a % b), a, b);
		}
		
		#endregion // Rem
		
		#region Neg
		
		[Row(0)]
		[Row(1)]
		[Row(sbyte.MinValue)]
		[Row(sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1)]
		[Row(-1)]
		[Row(sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void NegSbyte(sbyte first)
		{
			this.arithmeticTests.Neg(-first, first);
		}
		
		#endregion // Neg
		
		#region Ret
		
		[Row(0)]
		[Row(1)]
		[Row(sbyte.MinValue)]
		[Row(sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1)]
		[Row(-1)]
		[Row(sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void RetSbyte(sbyte value)
		{
			this.arithmeticTests.Ret(value);
		}
		
		#endregion // Ret
		
		#region And
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void AndSbyteSbyte(sbyte first, sbyte second)
		{
			this.logicTests.And((first & second), first, second);
		}
		
		#endregion // And
		
		#region Or
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void OrSbyteSbyte(sbyte first, sbyte second)
		{
			this.logicTests.Or((first | second), first, second);
		}
		
		#endregion // Or
		
		#region Xor
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void XorSbyteSbyte(sbyte first, sbyte second)
		{
			this.logicTests.Xor((first ^ second), first, second);
		}
		
		#endregion // Xor
		
		#region Shl
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, 3)]
		[Row(0, 4)]
		[Row(0, 5)]
		[Row(0, 6)]
		[Row(0, 7)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, 3)]
		[Row(1, 4)]
		[Row(1, 5)]
		[Row(1, 6)]
		[Row(1, 7)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, 3)]
		[Row(sbyte.MinValue, 4)]
		[Row(sbyte.MinValue, 5)]
		[Row(sbyte.MinValue, 6)]
		[Row(sbyte.MinValue, 7)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, 3)]
		[Row(sbyte.MaxValue, 4)]
		[Row(sbyte.MaxValue, 5)]
		[Row(sbyte.MaxValue, 6)]
		[Row(sbyte.MaxValue, 7)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, 3)]
		[Row(sbyte.MinValue + 1, 4)]
		[Row(sbyte.MinValue + 1, 5)]
		[Row(sbyte.MinValue + 1, 6)]
		[Row(sbyte.MinValue + 1, 7)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, 3)]
		[Row(sbyte.MaxValue - 1, 4)]
		[Row(sbyte.MaxValue - 1, 5)]
		[Row(sbyte.MaxValue - 1, 6)]
		[Row(sbyte.MaxValue - 1, 7)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, 3)]
		[Row(-1, 4)]
		[Row(-1, 5)]
		[Row(-1, 6)]
		[Row(-1, 7)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, 3)]
		[Row(sbyte.MinValue + 2, 4)]
		[Row(sbyte.MinValue + 2, 5)]
		[Row(sbyte.MinValue + 2, 6)]
		[Row(sbyte.MinValue + 2, 7)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void ShlSbyteSbyte(sbyte first, sbyte second)
		{
			this.logicTests.Shl((first << second), first, second);
		}
		
		#endregion // Shl
		
		#region Shr
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, 3)]
		[Row(0, 4)]
		[Row(0, 5)]
		[Row(0, 6)]
		[Row(0, 7)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, 3)]
		[Row(1, 4)]
		[Row(1, 5)]
		[Row(1, 6)]
		[Row(1, 7)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, 3)]
		[Row(sbyte.MinValue, 4)]
		[Row(sbyte.MinValue, 5)]
		[Row(sbyte.MinValue, 6)]
		[Row(sbyte.MinValue, 7)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, 3)]
		[Row(sbyte.MaxValue, 4)]
		[Row(sbyte.MaxValue, 5)]
		[Row(sbyte.MaxValue, 6)]
		[Row(sbyte.MaxValue, 7)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, 3)]
		[Row(sbyte.MinValue + 1, 4)]
		[Row(sbyte.MinValue + 1, 5)]
		[Row(sbyte.MinValue + 1, 6)]
		[Row(sbyte.MinValue + 1, 7)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, 3)]
		[Row(sbyte.MaxValue - 1, 4)]
		[Row(sbyte.MaxValue - 1, 5)]
		[Row(sbyte.MaxValue - 1, 6)]
		[Row(sbyte.MaxValue - 1, 7)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, 3)]
		[Row(-1, 4)]
		[Row(-1, 5)]
		[Row(-1, 6)]
		[Row(-1, 7)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, 3)]
		[Row(sbyte.MinValue + 2, 4)]
		[Row(sbyte.MinValue + 2, 5)]
		[Row(sbyte.MinValue + 2, 6)]
		[Row(sbyte.MinValue + 2, 7)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void ShrSbyteSbyte(sbyte first, sbyte second)
		{
			this.logicTests.Shr((first >> second), first, second);
		}
		
		#endregion // Shr
		
		#region Ceq
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void CeqSbyteSbyte(sbyte first, sbyte second)
		{
			this.comparisonTests.Ceq((first == second), first, second);
		}
		
		#endregion // Ceq
		
		#region Cgt
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void CgtSbyteSbyte(sbyte first, sbyte second)
		{
			this.comparisonTests.Cgt((first > second), first, second);
		}
		
		#endregion // Cgt
		
		#region Clt
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void CltSbyteSbyte(sbyte first, sbyte second)
		{
			this.comparisonTests.Clt((first < second), first, second);
		}
		
		#endregion // Clt
		
		#region Cge
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void CgeSbyteSbyte(sbyte first, sbyte second)
		{
			this.comparisonTests.Cge((first >= second), first, second);
		}
		
		#endregion // Cge
		
		#region Cle
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, -1)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void CleSbyteSbyte(sbyte first, sbyte second)
		{
			this.comparisonTests.Cle((first <= second), first, second);
		}
		
		#endregion // Cle
		
		#region Newarr
		
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void NewarrSbyte()
		{
			this.arrayTests.Newarr();
		}
		
		#endregion // Newarr
		
		#region Ldlen
		
		[Row(0)]
		[Row(1)]
		[Row(2)]
		[Row(4)]
		[Row(7)]
		[Row(8)]
		[Row(10)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void LdlenSbyte(int length)
		{
			this.arrayTests.Ldlen(length);
		}
		
		#endregion // Ldlen
		
		#region Stelem
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, -1)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(4, 0)]
		[Row(4, 1)]
		[Row(4, sbyte.MinValue)]
		[Row(4, sbyte.MaxValue)]
		[Row(4, sbyte.MinValue + 1)]
		[Row(4, sbyte.MaxValue - 1)]
		[Row(4, -1)]
		[Row(4, sbyte.MinValue + 2)]
		[Row(7, 0)]
		[Row(7, 1)]
		[Row(7, sbyte.MinValue)]
		[Row(7, sbyte.MaxValue)]
		[Row(7, sbyte.MinValue + 1)]
		[Row(7, sbyte.MaxValue - 1)]
		[Row(7, -1)]
		[Row(7, sbyte.MinValue + 2)]
		[Row(8, 0)]
		[Row(8, 1)]
		[Row(8, sbyte.MinValue)]
		[Row(8, sbyte.MaxValue)]
		[Row(8, sbyte.MinValue + 1)]
		[Row(8, sbyte.MaxValue - 1)]
		[Row(8, -1)]
		[Row(8, sbyte.MinValue + 2)]
		[Row(10, 0)]
		[Row(10, 1)]
		[Row(10, sbyte.MinValue)]
		[Row(10, sbyte.MaxValue)]
		[Row(10, sbyte.MinValue + 1)]
		[Row(10, sbyte.MaxValue - 1)]
		[Row(10, -1)]
		[Row(10, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void StelemSbyte(int index, sbyte value)
		{
			this.arrayTests.Stelem(index, value);
		}
		
		#endregion // Stelem
		
		#region Ldelem
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, -1)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(4, 0)]
		[Row(4, 1)]
		[Row(4, sbyte.MinValue)]
		[Row(4, sbyte.MaxValue)]
		[Row(4, sbyte.MinValue + 1)]
		[Row(4, sbyte.MaxValue - 1)]
		[Row(4, -1)]
		[Row(4, sbyte.MinValue + 2)]
		[Row(7, 0)]
		[Row(7, 1)]
		[Row(7, sbyte.MinValue)]
		[Row(7, sbyte.MaxValue)]
		[Row(7, sbyte.MinValue + 1)]
		[Row(7, sbyte.MaxValue - 1)]
		[Row(7, -1)]
		[Row(7, sbyte.MinValue + 2)]
		[Row(8, 0)]
		[Row(8, 1)]
		[Row(8, sbyte.MinValue)]
		[Row(8, sbyte.MaxValue)]
		[Row(8, sbyte.MinValue + 1)]
		[Row(8, sbyte.MaxValue - 1)]
		[Row(8, -1)]
		[Row(8, sbyte.MinValue + 2)]
		[Row(10, 0)]
		[Row(10, 1)]
		[Row(10, sbyte.MinValue)]
		[Row(10, sbyte.MaxValue)]
		[Row(10, sbyte.MinValue + 1)]
		[Row(10, sbyte.MaxValue - 1)]
		[Row(10, -1)]
		[Row(10, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void LdelemSbyte(int index, sbyte value)
		{
			this.arrayTests.Ldelem(index, value);
		}
		
		#endregion // Ldelem
		
		#region Ldelema
		
		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, -1)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, -1)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, -1)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(4, 0)]
		[Row(4, 1)]
		[Row(4, sbyte.MinValue)]
		[Row(4, sbyte.MaxValue)]
		[Row(4, sbyte.MinValue + 1)]
		[Row(4, sbyte.MaxValue - 1)]
		[Row(4, -1)]
		[Row(4, sbyte.MinValue + 2)]
		[Row(7, 0)]
		[Row(7, 1)]
		[Row(7, sbyte.MinValue)]
		[Row(7, sbyte.MaxValue)]
		[Row(7, sbyte.MinValue + 1)]
		[Row(7, sbyte.MaxValue - 1)]
		[Row(7, -1)]
		[Row(7, sbyte.MinValue + 2)]
		[Row(8, 0)]
		[Row(8, 1)]
		[Row(8, sbyte.MinValue)]
		[Row(8, sbyte.MaxValue)]
		[Row(8, sbyte.MinValue + 1)]
		[Row(8, sbyte.MaxValue - 1)]
		[Row(8, -1)]
		[Row(8, sbyte.MinValue + 2)]
		[Row(10, 0)]
		[Row(10, 1)]
		[Row(10, sbyte.MinValue)]
		[Row(10, sbyte.MaxValue)]
		[Row(10, sbyte.MinValue + 1)]
		[Row(10, sbyte.MaxValue - 1)]
		[Row(10, -1)]
		[Row(10, sbyte.MinValue + 2)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void LdelemaSbyte(int index, sbyte value)
		{
			this.arrayTests.Ldelema(index, value);
		}
		
		#endregion // Ldelema
		
	}
}
