/*
 * (c) 2008 MOSA - The Managed Operating System Alliance
 *
 * Licensed under the terms of the New BSD License.
 *
 * Authors:
 *  Michael Fröhlich (aka grover, <mailto:sharpos@michaelruck.de>)
 *  
 */

using System;

using MbUnit.Framework;

namespace Test.Mosa.Runtime.CompilerFramework.CLI
{
    [TestFixture]
    [Importance(Importance.Critical)]
    [Category(@"Basic types")]
    [Description(@"Tests support for the basic type System.SByte")]
    public class SByteFixture : RuntimeFixture
    {
        private readonly ArithmeticInstructionTestRunner<int, sbyte> arithmeticTests = new ArithmeticInstructionTestRunner<int, sbyte>
        {
            ExpectedTypeName = @"int",
            TypeName = @"sbyte"
        };

		private readonly BinaryLogicInstructionTestRunner<int, sbyte, sbyte> logicTests = new BinaryLogicInstructionTestRunner<int, sbyte, sbyte>
		{
			ExpectedTypeName = @"int",
			TypeName = @"sbyte",
			ShiftTypeName = @"sbyte",
			IncludeNot = false,
			IncludeComp = false
		};

        private readonly ComparisonInstructionTestRunner<sbyte> comparisonTests = new ComparisonInstructionTestRunner<sbyte>
        {
            TypeName = @"sbyte"
        };

        private readonly SZArrayInstructionTestRunner<sbyte> arrayTests = new SZArrayInstructionTestRunner<sbyte>
        {
            TypeName = @"sbyte"
        };

		#region Add

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		[Row(0, -1)]
		[Row(0, -2)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(0, -17)]
		[Row(0, -123)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		[Row(1, -1)]
		[Row(1, -2)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(1, -17)]
		[Row(1, -123)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		[Row(2, -1)]
		[Row(2, -2)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(2, -17)]
		[Row(2, -123)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, -2)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, -17)]
		[Row(sbyte.MinValue, -123)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, -2)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, -17)]
		[Row(sbyte.MaxValue, -123)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, -2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, -17)]
		[Row(sbyte.MinValue + 1, -123)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, -2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, -17)]
		[Row(sbyte.MaxValue - 1, -123)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, sbyte.MinValue)]
		[Row(17, sbyte.MaxValue)]
		[Row(17, sbyte.MinValue + 1)]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		[Row(17, -1)]
		[Row(17, -2)]
		[Row(17, sbyte.MinValue + 2)]
		[Row(17, -17)]
		[Row(17, -123)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, sbyte.MinValue)]
		[Row(123, sbyte.MaxValue)]
		[Row(123, sbyte.MinValue + 1)]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		[Row(123, -1)]
		[Row(123, -2)]
		[Row(123, sbyte.MinValue + 2)]
		[Row(123, -17)]
		[Row(123, -123)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		[Row(-1, -1)]
		[Row(-1, -2)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(-1, -17)]
		[Row(-1, -123)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, sbyte.MinValue)]
		[Row(-2, sbyte.MaxValue)]
		[Row(-2, sbyte.MinValue + 1)]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		[Row(-2, -1)]
		[Row(-2, -2)]
		[Row(-2, sbyte.MinValue + 2)]
		[Row(-2, -17)]
		[Row(-2, -123)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, -2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, -17)]
		[Row(sbyte.MinValue + 2, -123)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, sbyte.MinValue)]
		[Row(-17, sbyte.MaxValue)]
		[Row(-17, sbyte.MinValue + 1)]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		[Row(-17, -1)]
		[Row(-17, -2)]
		[Row(-17, sbyte.MinValue + 2)]
		[Row(-17, -17)]
		[Row(-17, -123)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, sbyte.MinValue)]
		[Row(-123, sbyte.MaxValue)]
		[Row(-123, sbyte.MinValue + 1)]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		[Row(-123, -1)]
		[Row(-123, -2)]
		[Row(-123, sbyte.MinValue + 2)]
		[Row(-123, -17)]
		[Row(-123, -123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Add(sbyte a, sbyte b)
		{
			this.arithmeticTests.Add((a + b), a, b);
		}

		#endregion // Add

		#region Sub

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		[Row(0, -1)]
		[Row(0, -2)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(0, -17)]
		[Row(0, -123)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		[Row(1, -1)]
		[Row(1, -2)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(1, -17)]
		[Row(1, -123)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		[Row(2, -1)]
		[Row(2, -2)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(2, -17)]
		[Row(2, -123)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, -2)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, -17)]
		[Row(sbyte.MinValue, -123)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, -2)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, -17)]
		[Row(sbyte.MaxValue, -123)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, -2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, -17)]
		[Row(sbyte.MinValue + 1, -123)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, -2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, -17)]
		[Row(sbyte.MaxValue - 1, -123)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, sbyte.MinValue)]
		[Row(17, sbyte.MaxValue)]
		[Row(17, sbyte.MinValue + 1)]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		[Row(17, -1)]
		[Row(17, -2)]
		[Row(17, sbyte.MinValue + 2)]
		[Row(17, -17)]
		[Row(17, -123)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, sbyte.MinValue)]
		[Row(123, sbyte.MaxValue)]
		[Row(123, sbyte.MinValue + 1)]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		[Row(123, -1)]
		[Row(123, -2)]
		[Row(123, sbyte.MinValue + 2)]
		[Row(123, -17)]
		[Row(123, -123)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		[Row(-1, -1)]
		[Row(-1, -2)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(-1, -17)]
		[Row(-1, -123)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, sbyte.MinValue)]
		[Row(-2, sbyte.MaxValue)]
		[Row(-2, sbyte.MinValue + 1)]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		[Row(-2, -1)]
		[Row(-2, -2)]
		[Row(-2, sbyte.MinValue + 2)]
		[Row(-2, -17)]
		[Row(-2, -123)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, -2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, -17)]
		[Row(sbyte.MinValue + 2, -123)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, sbyte.MinValue)]
		[Row(-17, sbyte.MaxValue)]
		[Row(-17, sbyte.MinValue + 1)]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		[Row(-17, -1)]
		[Row(-17, -2)]
		[Row(-17, sbyte.MinValue + 2)]
		[Row(-17, -17)]
		[Row(-17, -123)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, sbyte.MinValue)]
		[Row(-123, sbyte.MaxValue)]
		[Row(-123, sbyte.MinValue + 1)]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		[Row(-123, -1)]
		[Row(-123, -2)]
		[Row(-123, sbyte.MinValue + 2)]
		[Row(-123, -17)]
		[Row(-123, -123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Sub(sbyte a, sbyte b)
		{
			this.arithmeticTests.Sub((a - b), a, b);
		}

		#endregion // Sub

		#region Mul

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		[Row(0, -1)]
		[Row(0, -2)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(0, -17)]
		[Row(0, -123)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		[Row(1, -1)]
		[Row(1, -2)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(1, -17)]
		[Row(1, -123)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		[Row(2, -1)]
		[Row(2, -2)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(2, -17)]
		[Row(2, -123)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, -2)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, -17)]
		[Row(sbyte.MinValue, -123)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, -2)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, -17)]
		[Row(sbyte.MaxValue, -123)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, -2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, -17)]
		[Row(sbyte.MinValue + 1, -123)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, -2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, -17)]
		[Row(sbyte.MaxValue - 1, -123)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, sbyte.MinValue)]
		[Row(17, sbyte.MaxValue)]
		[Row(17, sbyte.MinValue + 1)]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		[Row(17, -1)]
		[Row(17, -2)]
		[Row(17, sbyte.MinValue + 2)]
		[Row(17, -17)]
		[Row(17, -123)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, sbyte.MinValue)]
		[Row(123, sbyte.MaxValue)]
		[Row(123, sbyte.MinValue + 1)]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		[Row(123, -1)]
		[Row(123, -2)]
		[Row(123, sbyte.MinValue + 2)]
		[Row(123, -17)]
		[Row(123, -123)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		[Row(-1, -1)]
		[Row(-1, -2)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(-1, -17)]
		[Row(-1, -123)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, sbyte.MinValue)]
		[Row(-2, sbyte.MaxValue)]
		[Row(-2, sbyte.MinValue + 1)]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		[Row(-2, -1)]
		[Row(-2, -2)]
		[Row(-2, sbyte.MinValue + 2)]
		[Row(-2, -17)]
		[Row(-2, -123)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, -2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, -17)]
		[Row(sbyte.MinValue + 2, -123)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, sbyte.MinValue)]
		[Row(-17, sbyte.MaxValue)]
		[Row(-17, sbyte.MinValue + 1)]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		[Row(-17, -1)]
		[Row(-17, -2)]
		[Row(-17, sbyte.MinValue + 2)]
		[Row(-17, -17)]
		[Row(-17, -123)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, sbyte.MinValue)]
		[Row(-123, sbyte.MaxValue)]
		[Row(-123, sbyte.MinValue + 1)]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		[Row(-123, -1)]
		[Row(-123, -2)]
		[Row(-123, sbyte.MinValue + 2)]
		[Row(-123, -17)]
		[Row(-123, -123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Mul(sbyte a, sbyte b)
		{
			this.arithmeticTests.Mul((a * b), a, b);
		}

		#endregion // Mul

		#region Div

		[Row(0, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		[Row(0, -1)]
		[Row(0, -2)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(0, -17)]
		[Row(0, -123)]
		[Row(1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		[Row(1, -1)]
		[Row(1, -2)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(1, -17)]
		[Row(1, -123)]
		[Row(2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		[Row(2, -1)]
		[Row(2, -2)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(2, -17)]
		[Row(2, -123)]
		[Row(sbyte.MinValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, -2)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, -17)]
		[Row(sbyte.MinValue, -123)]
		[Row(sbyte.MaxValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, -2)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, -17)]
		[Row(sbyte.MaxValue, -123)]
		[Row(sbyte.MinValue + 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, -2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, -17)]
		[Row(sbyte.MinValue + 1, -123)]
		[Row(sbyte.MaxValue - 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, -2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, -17)]
		[Row(sbyte.MaxValue - 1, -123)]
		[Row(17, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, sbyte.MinValue)]
		[Row(17, sbyte.MaxValue)]
		[Row(17, sbyte.MinValue + 1)]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		[Row(17, -1)]
		[Row(17, -2)]
		[Row(17, sbyte.MinValue + 2)]
		[Row(17, -17)]
		[Row(17, -123)]
		[Row(123, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, sbyte.MinValue)]
		[Row(123, sbyte.MaxValue)]
		[Row(123, sbyte.MinValue + 1)]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		[Row(123, -1)]
		[Row(123, -2)]
		[Row(123, sbyte.MinValue + 2)]
		[Row(123, -17)]
		[Row(123, -123)]
		[Row(-1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		[Row(-1, -1)]
		[Row(-1, -2)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(-1, -17)]
		[Row(-1, -123)]
		[Row(-2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, sbyte.MinValue)]
		[Row(-2, sbyte.MaxValue)]
		[Row(-2, sbyte.MinValue + 1)]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		[Row(-2, -1)]
		[Row(-2, -2)]
		[Row(-2, sbyte.MinValue + 2)]
		[Row(-2, -17)]
		[Row(-2, -123)]
		[Row(sbyte.MinValue + 2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, -2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, -17)]
		[Row(sbyte.MinValue + 2, -123)]
		[Row(-17, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, sbyte.MinValue)]
		[Row(-17, sbyte.MaxValue)]
		[Row(-17, sbyte.MinValue + 1)]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		[Row(-17, -1)]
		[Row(-17, -2)]
		[Row(-17, sbyte.MinValue + 2)]
		[Row(-17, -17)]
		[Row(-17, -123)]
		[Row(-123, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, sbyte.MinValue)]
		[Row(-123, sbyte.MaxValue)]
		[Row(-123, sbyte.MinValue + 1)]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		[Row(-123, -1)]
		[Row(-123, -2)]
		[Row(-123, sbyte.MinValue + 2)]
		[Row(-123, -17)]
		[Row(-123, -123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Div(sbyte a, sbyte b)
		{
			this.arithmeticTests.Div((a / b), a, b);
		}

		#endregion // Div

		#region Rem

		[Row(0, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(0, 1)]
		[Row(0, 2)]
		//[Row(0, -128, ExpectedException = typeof(OverflowException))]
		[Row(0, sbyte.MaxValue)]
		//[Row(0, -127, ExpectedException = typeof(OverflowException))]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		//[Row(0, -1, ExpectedException = typeof(OverflowException))]
		//[Row(0, -2, ExpectedException = typeof(OverflowException))]
		//[Row(0, -126, ExpectedException = typeof(OverflowException))]
		//[Row(0, -17, ExpectedException = typeof(OverflowException))]
		//[Row(0, -123, ExpectedException = typeof(OverflowException))]
		[Row(1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(1, 1)]
		[Row(1, 2)]
		//[Row(1, -128, ExpectedException = typeof(OverflowException))]
		[Row(1, sbyte.MaxValue)]
		//[Row(1, -127, ExpectedException = typeof(OverflowException))]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		//[Row(1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(1, -2, ExpectedException = typeof(OverflowException))]
		//[Row(1, -126, ExpectedException = typeof(OverflowException))]
		//[Row(1, -17, ExpectedException = typeof(OverflowException))]
		//[Row(1, -123, ExpectedException = typeof(OverflowException))]
		[Row(2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(2, 1)]
		[Row(2, 2)]
		//[Row(2, -128, ExpectedException = typeof(OverflowException))]
		[Row(2, sbyte.MaxValue)]
		//[Row(2, -127, ExpectedException = typeof(OverflowException))]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		//[Row(2, -1, ExpectedException = typeof(OverflowException))]
		//[Row(2, -2, ExpectedException = typeof(OverflowException))]
		//[Row(2, -126, ExpectedException = typeof(OverflowException))]
		//[Row(2, -17, ExpectedException = typeof(OverflowException))]
		//[Row(2, -123, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		//[Row(sbyte.MinValue, -128, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		//[Row(sbyte.MinValue, -127, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		//[Row(sbyte.MinValue, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue, -2, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue, -126, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue, -17, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue, -123, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		//[Row(sbyte.MaxValue, -128, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		//[Row(sbyte.MaxValue, -127, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		//[Row(sbyte.MaxValue, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue, -2, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue, -126, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue, -17, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue, -123, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		//[Row(sbyte.MinValue + 1, -128, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		//[Row(sbyte.MinValue + 1, -127, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		//[Row(sbyte.MinValue + 1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 1, -2, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 1, -126, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 1, -17, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 1, -123, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue - 1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		//[Row(sbyte.MaxValue - 1, -128, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		//[Row(sbyte.MaxValue - 1, -127, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		//[Row(sbyte.MaxValue - 1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue - 1, -2, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue - 1, -126, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue - 1, -17, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MaxValue - 1, -123, ExpectedException = typeof(OverflowException))]
		[Row(17, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(17, 1)]
		[Row(17, 2)]
		//[Row(17, -128, ExpectedException = typeof(OverflowException))]
		[Row(17, sbyte.MaxValue)]
		//[Row(17, -127, ExpectedException = typeof(OverflowException))]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		//[Row(17, -1, ExpectedException = typeof(OverflowException))]
		//[Row(17, -2, ExpectedException = typeof(OverflowException))]
		//[Row(17, -126, ExpectedException = typeof(OverflowException))]
		//[Row(17, -17, ExpectedException = typeof(OverflowException))]
		//[Row(17, -123, ExpectedException = typeof(OverflowException))]
		[Row(123, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(123, 1)]
		[Row(123, 2)]
		//[Row(123, -128, ExpectedException = typeof(OverflowException))]
		[Row(123, sbyte.MaxValue)]
		//[Row(123, -127, ExpectedException = typeof(OverflowException))]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		//[Row(123, -1, ExpectedException = typeof(OverflowException))]
		//[Row(123, -2, ExpectedException = typeof(OverflowException))]
		//[Row(123, -126, ExpectedException = typeof(OverflowException))]
		//[Row(123, -17, ExpectedException = typeof(OverflowException))]
		//[Row(123, -123, ExpectedException = typeof(OverflowException))]
		[Row(-1, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-1, 1)]
		[Row(-1, 2)]
		//[Row(-1, -128, ExpectedException = typeof(OverflowException))]
		[Row(-1, sbyte.MaxValue)]
		//[Row(-1, -127, ExpectedException = typeof(OverflowException))]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		//[Row(-1, -1, ExpectedException = typeof(OverflowException))]
		//[Row(-1, -2, ExpectedException = typeof(OverflowException))]
		//[Row(-1, -126, ExpectedException = typeof(OverflowException))]
		//[Row(-1, -17, ExpectedException = typeof(OverflowException))]
		//[Row(-1, -123, ExpectedException = typeof(OverflowException))]
		[Row(-2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-2, 1)]
		[Row(-2, 2)]
		//[Row(-2, -128, ExpectedException = typeof(OverflowException))]
		[Row(-2, sbyte.MaxValue)]
		//[Row(-2, -127, ExpectedException = typeof(OverflowException))]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		//[Row(-2, -1, ExpectedException = typeof(OverflowException))]
		//[Row(-2, -2, ExpectedException = typeof(OverflowException))]
		//[Row(-2, -126, ExpectedException = typeof(OverflowException))]
		//[Row(-2, -17, ExpectedException = typeof(OverflowException))]
		//[Row(-2, -123, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 2, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		//[Row(sbyte.MinValue + 2, -128, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		//[Row(sbyte.MinValue + 2, -127, ExpectedException = typeof(OverflowException))]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		//[Row(sbyte.MinValue + 2, -1, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 2, -2, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 2, -126, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 2, -17, ExpectedException = typeof(OverflowException))]
		//[Row(sbyte.MinValue + 2, -123, ExpectedException = typeof(OverflowException))]
		[Row(-17, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-17, 1)]
		[Row(-17, 2)]
		//[Row(-17, -128, ExpectedException = typeof(OverflowException))]
		[Row(-17, sbyte.MaxValue)]
		//[Row(-17, -127, ExpectedException = typeof(OverflowException))]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		//[Row(-17, -1, ExpectedException = typeof(OverflowException))]
		//[Row(-17, -2, ExpectedException = typeof(OverflowException))]
		//[Row(-17, -126, ExpectedException = typeof(OverflowException))]
		//[Row(-17, -17, ExpectedException = typeof(OverflowException))]
		//[Row(-17, -123, ExpectedException = typeof(OverflowException))]
		[Row(-123, 0, ExpectedException = typeof(DivideByZeroException))]
		[Row(-123, 1)]
		[Row(-123, 2)]
		//[Row(-123, -128, ExpectedException = typeof(OverflowException))]
		[Row(-123, sbyte.MaxValue)]
		//[Row(-123, -127, ExpectedException = typeof(OverflowException))]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		//[Row(-123, -1, ExpectedException = typeof(OverflowException))]
		//[Row(-123, -2, ExpectedException = typeof(OverflowException))]
		//[Row(-123, -126, ExpectedException = typeof(OverflowException))]
		//[Row(-123, -17, ExpectedException = typeof(OverflowException))]
		//[Row(-123, -123, ExpectedException = typeof(OverflowException))]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Rem(sbyte a, sbyte b)
		{
			this.arithmeticTests.Rem((a % b), a, b);
		}

		#endregion // Rem

		#region Neg

		[Row(0)]
		[Row(1)]
		[Row(2)]
		[Row(sbyte.MinValue)]
		[Row(sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1)]
		[Row(17)]
		[Row(123)]
		[Row(-1)]
		[Row(-2)]
		[Row(sbyte.MinValue + 2)]
		[Row(-17)]
		[Row(-123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Neg(sbyte first)
		{
			this.arithmeticTests.Neg(-first, first);
		}

		#endregion // Neg

		#region Ret

		[Row(0)]
		[Row(1)]
		[Row(2)]
		[Row(sbyte.MinValue)]
		[Row(sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1)]
		[Row(17)]
		[Row(123)]
		[Row(-1)]
		[Row(-2)]
		[Row(sbyte.MinValue + 2)]
		[Row(-17)]
		[Row(-123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Ret(sbyte value)
		{
			this.arithmeticTests.Ret(value);
		}

		#endregion // Ret

		#region And

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		[Row(0, -1)]
		[Row(0, -2)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(0, -17)]
		[Row(0, -123)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		[Row(1, -1)]
		[Row(1, -2)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(1, -17)]
		[Row(1, -123)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		[Row(2, -1)]
		[Row(2, -2)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(2, -17)]
		[Row(2, -123)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, -2)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, -17)]
		[Row(sbyte.MinValue, -123)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, -2)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, -17)]
		[Row(sbyte.MaxValue, -123)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, -2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, -17)]
		[Row(sbyte.MinValue + 1, -123)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, -2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, -17)]
		[Row(sbyte.MaxValue - 1, -123)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, sbyte.MinValue)]
		[Row(17, sbyte.MaxValue)]
		[Row(17, sbyte.MinValue + 1)]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		[Row(17, -1)]
		[Row(17, -2)]
		[Row(17, sbyte.MinValue + 2)]
		[Row(17, -17)]
		[Row(17, -123)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, sbyte.MinValue)]
		[Row(123, sbyte.MaxValue)]
		[Row(123, sbyte.MinValue + 1)]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		[Row(123, -1)]
		[Row(123, -2)]
		[Row(123, sbyte.MinValue + 2)]
		[Row(123, -17)]
		[Row(123, -123)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		[Row(-1, -1)]
		[Row(-1, -2)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(-1, -17)]
		[Row(-1, -123)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, sbyte.MinValue)]
		[Row(-2, sbyte.MaxValue)]
		[Row(-2, sbyte.MinValue + 1)]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		[Row(-2, -1)]
		[Row(-2, -2)]
		[Row(-2, sbyte.MinValue + 2)]
		[Row(-2, -17)]
		[Row(-2, -123)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, -2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, -17)]
		[Row(sbyte.MinValue + 2, -123)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, sbyte.MinValue)]
		[Row(-17, sbyte.MaxValue)]
		[Row(-17, sbyte.MinValue + 1)]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		[Row(-17, -1)]
		[Row(-17, -2)]
		[Row(-17, sbyte.MinValue + 2)]
		[Row(-17, -17)]
		[Row(-17, -123)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, sbyte.MinValue)]
		[Row(-123, sbyte.MaxValue)]
		[Row(-123, sbyte.MinValue + 1)]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		[Row(-123, -1)]
		[Row(-123, -2)]
		[Row(-123, sbyte.MinValue + 2)]
		[Row(-123, -17)]
		[Row(-123, -123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void And(sbyte first, sbyte second)
		{
			this.logicTests.And((first & second), first, second);
		}

		#endregion // And

		#region Or

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		[Row(0, -1)]
		[Row(0, -2)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(0, -17)]
		[Row(0, -123)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		[Row(1, -1)]
		[Row(1, -2)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(1, -17)]
		[Row(1, -123)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		[Row(2, -1)]
		[Row(2, -2)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(2, -17)]
		[Row(2, -123)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, -2)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, -17)]
		[Row(sbyte.MinValue, -123)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, -2)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, -17)]
		[Row(sbyte.MaxValue, -123)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, -2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, -17)]
		[Row(sbyte.MinValue + 1, -123)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, -2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, -17)]
		[Row(sbyte.MaxValue - 1, -123)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, sbyte.MinValue)]
		[Row(17, sbyte.MaxValue)]
		[Row(17, sbyte.MinValue + 1)]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		[Row(17, -1)]
		[Row(17, -2)]
		[Row(17, sbyte.MinValue + 2)]
		[Row(17, -17)]
		[Row(17, -123)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, sbyte.MinValue)]
		[Row(123, sbyte.MaxValue)]
		[Row(123, sbyte.MinValue + 1)]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		[Row(123, -1)]
		[Row(123, -2)]
		[Row(123, sbyte.MinValue + 2)]
		[Row(123, -17)]
		[Row(123, -123)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		[Row(-1, -1)]
		[Row(-1, -2)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(-1, -17)]
		[Row(-1, -123)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, sbyte.MinValue)]
		[Row(-2, sbyte.MaxValue)]
		[Row(-2, sbyte.MinValue + 1)]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		[Row(-2, -1)]
		[Row(-2, -2)]
		[Row(-2, sbyte.MinValue + 2)]
		[Row(-2, -17)]
		[Row(-2, -123)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, -2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, -17)]
		[Row(sbyte.MinValue + 2, -123)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, sbyte.MinValue)]
		[Row(-17, sbyte.MaxValue)]
		[Row(-17, sbyte.MinValue + 1)]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		[Row(-17, -1)]
		[Row(-17, -2)]
		[Row(-17, sbyte.MinValue + 2)]
		[Row(-17, -17)]
		[Row(-17, -123)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, sbyte.MinValue)]
		[Row(-123, sbyte.MaxValue)]
		[Row(-123, sbyte.MinValue + 1)]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		[Row(-123, -1)]
		[Row(-123, -2)]
		[Row(-123, sbyte.MinValue + 2)]
		[Row(-123, -17)]
		[Row(-123, -123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Or(sbyte first, sbyte second)
		{
			this.logicTests.Or((first | second), first, second);
		}

		#endregion // Or

		#region Xor

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, sbyte.MinValue)]
		[Row(0, sbyte.MaxValue)]
		[Row(0, sbyte.MinValue + 1)]
		[Row(0, sbyte.MaxValue - 1)]
		[Row(0, 17)]
		[Row(0, 123)]
		[Row(0, -1)]
		[Row(0, -2)]
		[Row(0, sbyte.MinValue + 2)]
		[Row(0, -17)]
		[Row(0, -123)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, sbyte.MinValue)]
		[Row(1, sbyte.MaxValue)]
		[Row(1, sbyte.MinValue + 1)]
		[Row(1, sbyte.MaxValue - 1)]
		[Row(1, 17)]
		[Row(1, 123)]
		[Row(1, -1)]
		[Row(1, -2)]
		[Row(1, sbyte.MinValue + 2)]
		[Row(1, -17)]
		[Row(1, -123)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, sbyte.MinValue)]
		[Row(2, sbyte.MaxValue)]
		[Row(2, sbyte.MinValue + 1)]
		[Row(2, sbyte.MaxValue - 1)]
		[Row(2, 17)]
		[Row(2, 123)]
		[Row(2, -1)]
		[Row(2, -2)]
		[Row(2, sbyte.MinValue + 2)]
		[Row(2, -17)]
		[Row(2, -123)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, sbyte.MinValue)]
		[Row(sbyte.MinValue, sbyte.MaxValue)]
		[Row(sbyte.MinValue, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue, 17)]
		[Row(sbyte.MinValue, 123)]
		[Row(sbyte.MinValue, -1)]
		[Row(sbyte.MinValue, -2)]
		[Row(sbyte.MinValue, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue, -17)]
		[Row(sbyte.MinValue, -123)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, sbyte.MinValue)]
		[Row(sbyte.MaxValue, sbyte.MaxValue)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue, 17)]
		[Row(sbyte.MaxValue, 123)]
		[Row(sbyte.MaxValue, -1)]
		[Row(sbyte.MaxValue, -2)]
		[Row(sbyte.MaxValue, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue, -17)]
		[Row(sbyte.MaxValue, -123)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 1, 17)]
		[Row(sbyte.MinValue + 1, 123)]
		[Row(sbyte.MinValue + 1, -1)]
		[Row(sbyte.MinValue + 1, -2)]
		[Row(sbyte.MinValue + 1, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 1, -17)]
		[Row(sbyte.MinValue + 1, -123)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 1)]
		[Row(sbyte.MaxValue - 1, sbyte.MaxValue - 1)]
		[Row(sbyte.MaxValue - 1, 17)]
		[Row(sbyte.MaxValue - 1, 123)]
		[Row(sbyte.MaxValue - 1, -1)]
		[Row(sbyte.MaxValue - 1, -2)]
		[Row(sbyte.MaxValue - 1, sbyte.MinValue + 2)]
		[Row(sbyte.MaxValue - 1, -17)]
		[Row(sbyte.MaxValue - 1, -123)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, sbyte.MinValue)]
		[Row(17, sbyte.MaxValue)]
		[Row(17, sbyte.MinValue + 1)]
		[Row(17, sbyte.MaxValue - 1)]
		[Row(17, 17)]
		[Row(17, 123)]
		[Row(17, -1)]
		[Row(17, -2)]
		[Row(17, sbyte.MinValue + 2)]
		[Row(17, -17)]
		[Row(17, -123)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, sbyte.MinValue)]
		[Row(123, sbyte.MaxValue)]
		[Row(123, sbyte.MinValue + 1)]
		[Row(123, sbyte.MaxValue - 1)]
		[Row(123, 17)]
		[Row(123, 123)]
		[Row(123, -1)]
		[Row(123, -2)]
		[Row(123, sbyte.MinValue + 2)]
		[Row(123, -17)]
		[Row(123, -123)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, sbyte.MinValue)]
		[Row(-1, sbyte.MaxValue)]
		[Row(-1, sbyte.MinValue + 1)]
		[Row(-1, sbyte.MaxValue - 1)]
		[Row(-1, 17)]
		[Row(-1, 123)]
		[Row(-1, -1)]
		[Row(-1, -2)]
		[Row(-1, sbyte.MinValue + 2)]
		[Row(-1, -17)]
		[Row(-1, -123)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, sbyte.MinValue)]
		[Row(-2, sbyte.MaxValue)]
		[Row(-2, sbyte.MinValue + 1)]
		[Row(-2, sbyte.MaxValue - 1)]
		[Row(-2, 17)]
		[Row(-2, 123)]
		[Row(-2, -1)]
		[Row(-2, -2)]
		[Row(-2, sbyte.MinValue + 2)]
		[Row(-2, -17)]
		[Row(-2, -123)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 1)]
		[Row(sbyte.MinValue + 2, sbyte.MaxValue - 1)]
		[Row(sbyte.MinValue + 2, 17)]
		[Row(sbyte.MinValue + 2, 123)]
		[Row(sbyte.MinValue + 2, -1)]
		[Row(sbyte.MinValue + 2, -2)]
		[Row(sbyte.MinValue + 2, sbyte.MinValue + 2)]
		[Row(sbyte.MinValue + 2, -17)]
		[Row(sbyte.MinValue + 2, -123)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, sbyte.MinValue)]
		[Row(-17, sbyte.MaxValue)]
		[Row(-17, sbyte.MinValue + 1)]
		[Row(-17, sbyte.MaxValue - 1)]
		[Row(-17, 17)]
		[Row(-17, 123)]
		[Row(-17, -1)]
		[Row(-17, -2)]
		[Row(-17, sbyte.MinValue + 2)]
		[Row(-17, -17)]
		[Row(-17, -123)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, sbyte.MinValue)]
		[Row(-123, sbyte.MaxValue)]
		[Row(-123, sbyte.MinValue + 1)]
		[Row(-123, sbyte.MaxValue - 1)]
		[Row(-123, 17)]
		[Row(-123, 123)]
		[Row(-123, -1)]
		[Row(-123, -2)]
		[Row(-123, sbyte.MinValue + 2)]
		[Row(-123, -17)]
		[Row(-123, -123)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Xor(sbyte first, sbyte second)
		{
			this.logicTests.Xor((first ^ second), first, second);
		}

		#endregion // Xor

		#region Shl

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, 3)]
		[Row(0, 4)]
		[Row(0, 5)]
		[Row(0, 6)]
		[Row(0, 7)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, 3)]
		[Row(1, 4)]
		[Row(1, 5)]
		[Row(1, 6)]
		[Row(1, 7)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, 3)]
		[Row(2, 4)]
		[Row(2, 5)]
		[Row(2, 6)]
		[Row(2, 7)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, 3)]
		[Row(sbyte.MinValue, 4)]
		[Row(sbyte.MinValue, 5)]
		[Row(sbyte.MinValue, 6)]
		[Row(sbyte.MinValue, 7)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, 3)]
		[Row(sbyte.MaxValue, 4)]
		[Row(sbyte.MaxValue, 5)]
		[Row(sbyte.MaxValue, 6)]
		[Row(sbyte.MaxValue, 7)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, 3)]
		[Row(sbyte.MinValue + 1, 4)]
		[Row(sbyte.MinValue + 1, 5)]
		[Row(sbyte.MinValue + 1, 6)]
		[Row(sbyte.MinValue + 1, 7)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, 3)]
		[Row(sbyte.MaxValue - 1, 4)]
		[Row(sbyte.MaxValue - 1, 5)]
		[Row(sbyte.MaxValue - 1, 6)]
		[Row(sbyte.MaxValue - 1, 7)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, 3)]
		[Row(17, 4)]
		[Row(17, 5)]
		[Row(17, 6)]
		[Row(17, 7)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, 3)]
		[Row(123, 4)]
		[Row(123, 5)]
		[Row(123, 6)]
		[Row(123, 7)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, 3)]
		[Row(-1, 4)]
		[Row(-1, 5)]
		[Row(-1, 6)]
		[Row(-1, 7)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, 3)]
		[Row(-2, 4)]
		[Row(-2, 5)]
		[Row(-2, 6)]
		[Row(-2, 7)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, 3)]
		[Row(sbyte.MinValue + 2, 4)]
		[Row(sbyte.MinValue + 2, 5)]
		[Row(sbyte.MinValue + 2, 6)]
		[Row(sbyte.MinValue + 2, 7)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, 3)]
		[Row(-17, 4)]
		[Row(-17, 5)]
		[Row(-17, 6)]
		[Row(-17, 7)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, 3)]
		[Row(-123, 4)]
		[Row(-123, 5)]
		[Row(-123, 6)]
		[Row(-123, 7)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Shl(sbyte first, sbyte second)
		{
			this.logicTests.Shl((first << second), first, second);
		}

		#endregion // Shl

		#region Shr

		[Row(0, 0)]
		[Row(0, 1)]
		[Row(0, 2)]
		[Row(0, 3)]
		[Row(0, 4)]
		[Row(0, 5)]
		[Row(0, 6)]
		[Row(0, 7)]
		[Row(1, 0)]
		[Row(1, 1)]
		[Row(1, 2)]
		[Row(1, 3)]
		[Row(1, 4)]
		[Row(1, 5)]
		[Row(1, 6)]
		[Row(1, 7)]
		[Row(2, 0)]
		[Row(2, 1)]
		[Row(2, 2)]
		[Row(2, 3)]
		[Row(2, 4)]
		[Row(2, 5)]
		[Row(2, 6)]
		[Row(2, 7)]
		[Row(sbyte.MinValue, 0)]
		[Row(sbyte.MinValue, 1)]
		[Row(sbyte.MinValue, 2)]
		[Row(sbyte.MinValue, 3)]
		[Row(sbyte.MinValue, 4)]
		[Row(sbyte.MinValue, 5)]
		[Row(sbyte.MinValue, 6)]
		[Row(sbyte.MinValue, 7)]
		[Row(sbyte.MaxValue, 0)]
		[Row(sbyte.MaxValue, 1)]
		[Row(sbyte.MaxValue, 2)]
		[Row(sbyte.MaxValue, 3)]
		[Row(sbyte.MaxValue, 4)]
		[Row(sbyte.MaxValue, 5)]
		[Row(sbyte.MaxValue, 6)]
		[Row(sbyte.MaxValue, 7)]
		[Row(sbyte.MinValue + 1, 0)]
		[Row(sbyte.MinValue + 1, 1)]
		[Row(sbyte.MinValue + 1, 2)]
		[Row(sbyte.MinValue + 1, 3)]
		[Row(sbyte.MinValue + 1, 4)]
		[Row(sbyte.MinValue + 1, 5)]
		[Row(sbyte.MinValue + 1, 6)]
		[Row(sbyte.MinValue + 1, 7)]
		[Row(sbyte.MaxValue - 1, 0)]
		[Row(sbyte.MaxValue - 1, 1)]
		[Row(sbyte.MaxValue - 1, 2)]
		[Row(sbyte.MaxValue - 1, 3)]
		[Row(sbyte.MaxValue - 1, 4)]
		[Row(sbyte.MaxValue - 1, 5)]
		[Row(sbyte.MaxValue - 1, 6)]
		[Row(sbyte.MaxValue - 1, 7)]
		[Row(17, 0)]
		[Row(17, 1)]
		[Row(17, 2)]
		[Row(17, 3)]
		[Row(17, 4)]
		[Row(17, 5)]
		[Row(17, 6)]
		[Row(17, 7)]
		[Row(123, 0)]
		[Row(123, 1)]
		[Row(123, 2)]
		[Row(123, 3)]
		[Row(123, 4)]
		[Row(123, 5)]
		[Row(123, 6)]
		[Row(123, 7)]
		[Row(-1, 0)]
		[Row(-1, 1)]
		[Row(-1, 2)]
		[Row(-1, 3)]
		[Row(-1, 4)]
		[Row(-1, 5)]
		[Row(-1, 6)]
		[Row(-1, 7)]
		[Row(-2, 0)]
		[Row(-2, 1)]
		[Row(-2, 2)]
		[Row(-2, 3)]
		[Row(-2, 4)]
		[Row(-2, 5)]
		[Row(-2, 6)]
		[Row(-2, 7)]
		[Row(sbyte.MinValue + 2, 0)]
		[Row(sbyte.MinValue + 2, 1)]
		[Row(sbyte.MinValue + 2, 2)]
		[Row(sbyte.MinValue + 2, 3)]
		[Row(sbyte.MinValue + 2, 4)]
		[Row(sbyte.MinValue + 2, 5)]
		[Row(sbyte.MinValue + 2, 6)]
		[Row(sbyte.MinValue + 2, 7)]
		[Row(-17, 0)]
		[Row(-17, 1)]
		[Row(-17, 2)]
		[Row(-17, 3)]
		[Row(-17, 4)]
		[Row(-17, 5)]
		[Row(-17, 6)]
		[Row(-17, 7)]
		[Row(-123, 0)]
		[Row(-123, 1)]
		[Row(-123, 2)]
		[Row(-123, 3)]
		[Row(-123, 4)]
		[Row(-123, 5)]
		[Row(-123, 6)]
		[Row(-123, 7)]
		[Test, Author("tgiphil", "phil@thinkedge.com")]
		public void Shr(sbyte first, sbyte second)
		{
			this.logicTests.Shr((first >> second), first, second);
		}

		#endregion // Shr

        #region Ceq

        [Row(true, 0, 0)]
        [Row(false, 0, 1)]
        [Row(true, 1, 1)]
        [Row(false, 1, 0)]
        [Row(true, sbyte.MinValue, sbyte.MinValue)]
        [Row(true, sbyte.MaxValue, sbyte.MaxValue)]
        [Row(false, sbyte.MinValue, sbyte.MaxValue)]
        [Test, Author(@"Michael Fröhlich, sharpos@michaelruck.de")]
        public void Ceq(bool expectedValue, sbyte first, sbyte second)
        {
            this.comparisonTests.Ceq(expectedValue, first, second);
        }

        #endregion // Ceq

        #region Newarr

        [Test, Author(@"Michael Fröhlich, sharpos@michaelruck.de")]
        public void Newarr()
        {
            this.arrayTests.Newarr();
        }

        #endregion // Newarr

        #region Ldlen

        [Row(0)]
        [Row(1)]
        [Row(10)]
        [Test, Author(@"Michael Fröhlich, sharpos@michaelruck.de")]
        public void Ldlen(int length)
        {
            this.arrayTests.Ldlen(length);
        }

        #endregion // Ldlen

        #region Stelem

        [Row(0, SByte.MinValue)]
        [Row(0, -1)]
        [Row(0, 0)]
        [Row(0, 1)]
        [Row(0, SByte.MaxValue)]
        [Row(3, SByte.MinValue)]
        [Row(7, -1)]
        [Row(9, 0)]
        [Row(6, 1)]
        [Row(2, SByte.MaxValue)]
        [Test, Author(@"Michael Fröhlich, sharpos@michaelruck.de")]
        public void Stelem(int index, sbyte value)
        {
            this.arrayTests.Stelem(index, value);
        }

        #endregion // Stelem

        #region Ldelem

        [Row(0, SByte.MinValue)]
        [Row(0, -1)]
        [Row(0, 0)]
        [Row(0, 1)]
        [Row(0, SByte.MaxValue)]
        [Row(3, SByte.MinValue)]
        [Row(7, -1)]
        [Row(9, 0)]
        [Row(6, 1)]
        [Row(2, SByte.MaxValue)]
        [Test, Author(@"Michael Fröhlich, sharpos@michaelruck.de")]
        public void Ldelem(int index, sbyte value)
        {
            this.arrayTests.Ldelem(index, value);
        }

        #endregion // Ldelem

        #region Ldelema

        [Row(0, SByte.MinValue)]
        [Row(0, -1)]
        [Row(0, 0)]
        [Row(0, 1)]
        [Row(0, SByte.MaxValue)]
        [Row(3, SByte.MinValue)]
        [Row(7, -1)]
        [Row(9, 0)]
        [Row(6, 1)]
        [Row(2, SByte.MaxValue)]
        [Test, Author(@"Michael Fröhlich, sharpos@michaelruck.de")]
        public void Ldelema(int index, sbyte value)
        {
            this.arrayTests.Ldelema(index, value);
        }

        #endregion // Ldelema
    }
}
