// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Compiler.ARM32.Instructions;

/// <summary>
/// Mcr - Move from coprocessor to processor register
/// </summary>
public sealed class Mcr : ARM32Instruction
{
	internal Mcr()
		: base(1, 5)
	{
	}

	public override bool IsCommutative => true;

	public override void Emit(Node node, OpcodeEncoder opcodeEncoder)
	{
		System.Diagnostics.Debug.Assert(node.ResultCount == 1);
		System.Diagnostics.Debug.Assert(node.OperandCount == 5);
		System.Diagnostics.Debug.Assert(opcodeEncoder.CheckOpcodeAlignment());

		if (node.Operand1.IsConstant && node.Operand2.IsConstant && node.Operand3.IsConstant && node.Operand4.IsConstant && node.Operand5.IsConstant)
		{
			opcodeEncoder.Append4Bits(GetConditionCode(node.ConditionCode));
			opcodeEncoder.Append4Bits(0b1110);
			opcodeEncoder.AppendNBitImmediate(node.Operand2, 3, 0);
			opcodeEncoder.Append1Bit(0b0);
			opcodeEncoder.AppendNBitImmediate(node.Operand3, 4, 0);
			opcodeEncoder.Append4Bits(node.Result.Register.RegisterCode);
			opcodeEncoder.Append4Bits(node.Operand1.Register.RegisterCode);
			opcodeEncoder.AppendNBitImmediate(node.Operand5, 3, 0);
			opcodeEncoder.Append1Bit(0b1);
			opcodeEncoder.AppendNBitImmediate(node.Operand4, 4, 0);

			System.Diagnostics.Debug.Assert(opcodeEncoder.CheckOpcodeAlignment());
			return;
		}

		throw new Common.Exceptions.CompilerException($"Invalid Opcode: {node}");
	}
}
