namespace System.Formats.Asn1;

public enum UniversalTagNumber
{
	EndOfContents = 0,
	Boolean = 1,
	Integer = 2,
	BitString = 3,
	OctetString = 4,
	Null = 5,
	ObjectIdentifier = 6,
	ObjectDescriptor = 7,
	External = 8,
	InstanceOf = 8,
	Real = 9,
	Enumerated = 10,
	Embedded = 11,
	UTF8String = 12,
	RelativeObjectIdentifier = 13,
	Time = 14,
	Sequence = 16,
	SequenceOf = 16,
	Set = 17,
	SetOf = 17,
	NumericString = 18,
	PrintableString = 19,
	T61String = 20,
	TeletexString = 20,
	VideotexString = 21,
	IA5String = 22,
	UtcTime = 23,
	GeneralizedTime = 24,
	GraphicString = 25,
	ISO646String = 26,
	VisibleString = 26,
	GeneralString = 27,
	UniversalString = 28,
	UnrestrictedCharacterString = 29,
	BMPString = 30,
	Date = 31,
	TimeOfDay = 32,
	DateTime = 33,
	Duration = 34,
	ObjectIdentifierIRI = 35,
	RelativeObjectIdentifierIRI = 36
}
