PATH=C:\Program Files\Mono-2.4.2.1;%PATH%

call gmcs -lib:Bin -target:library -out:Bin\Mosa.ClassLib.dll ClassLib\*.cs 
call gmcs -lib:Bin -target:library -out:Bin\Mosa.DeviceSystem.dll -d:MONO -reference:Mosa.ClassLib.dll DeviceSystem\*.cs DeviceSystem\PCI\*.cs 
call gmcs -lib:Bin -target:library -out:Bin\Mosa.DeviceDrivers.dll -reference:Mosa.ClassLib.dll -reference:Mosa.DeviceSystem.dll DeviceDrivers\*.cs DeviceDrivers\ISA\*.cs DeviceDrivers\PCI\*.cs DeviceDrivers\ScanCodeMap\*.cs 
call gmcs -lib:Bin -target:library -out:Bin\Mosa.FileSystem.dll -reference:Mosa.ClassLib.dll -reference:Mosa.DeviceSystem.dll FileSystem\*.cs FileSystem\FAT\*.cs FileSystem\VFS\*.cs FileSystem\FAT\Find\*.cs 
call gmcs -lib:Bin -target:library -out:Bin\Mosa.EmulatedKernel.dll -reference:Mosa.ClassLib.dll -reference:Mosa.DeviceSystem.dll EmulatedKernel\*.cs 
call gmcs -lib:Bin -target:library -out:Bin\Mosa.EmulatedDevices.dll -unsafe -reference:Mosa.ClassLib.dll -reference:Mosa.DeviceSystem.dll -reference:Mosa.EmulatedKernel.dll -reference:System.dll -reference:System.Drawing.dll -reference:System.Windows.Forms.dll EmulatedDevices\*.cs EmulatedDevices\Emulated\*.cs EmulatedDevices\Synthetic\*.cs 
call gmcs -lib:Bin -target:library -out:Bin\Mosa.Pictor.dll Pictor\*.cs Pictor\Controls\*.cs Pictor\Math\*.cs Pictor\Objects\*.cs Pictor\Renderer\*.cs Pictor\Renderer\ColorTypes\*.cs Pictor\Renderer\PixelFormats\*.cs Pictor\Renderer\Scanline\*.cs Pictor\Renderer\Scanline\Scanlines\*.cs Pictor\Objects\Arcs\*.cs Pictor\Objects\Curves\*.cs Pictor\Objects\Primitives\*.cs Pictor\Objects\Splines\*.cs 
call gmcs -lib:Bin -target:exe -out:Bin\Emulator.exe -reference:Mosa.ClassLib.dll -reference:Mosa.DeviceSystem.dll -reference:Mosa.DeviceDrivers.dll -reference:Mosa.EmulatedKernel.dll -reference:Mosa.FileSystem.dll -reference:Mosa.EmulatedDevices.dll -reference:Mosa.Pictor.dll Emulator\*.cs 
call gmcs -lib:Bin -target:exe -out:Bin\MakeBootImage.exe -reference:Mosa.ClassLib.dll -reference:Mosa.DeviceSystem.dll -reference:Mosa.DeviceDrivers.dll -reference:Mosa.FileSystem.dll -reference:Mosa.EmulatedDevices.dll Tools\MakeBootImage\*.cs 
call gmcs -lib:Bin -target:library -unsafe -out:Bin\Mosa.Kernel.dll Kernel\*.cs Kernel\Memory\*.cs Kernel\Memory\X86\*.cs 
call gmcs -lib:Bin -target:library -unsafe -out:Bin\Mosa.RunTime.dll -reference:System.dll -reference:System.Data.dll -reference:System.Xml.dll -reference:Mosa.Kernel.dll RunTime\*.cs Runtime\CompilerFramework\*.cs Runtime\CompilerFramework\IL\*.cs Runtime\CompilerFramework\IR\*.cs Runtime\Linker\*.cs Runtime\Linker\Elf32\*.cs Runtime\Linker\Elf32\Sections\*.cs Runtime\Linker\Elf64\*.cs Runtime\Linker\Elf64\Sections\*.cs Runtime\Linker\PE\*.cs Runtime\Metadata\*.cs Runtime\Metadata\Blobs\*.cs Runtime\Metadata\Signatures\*.cs Runtime\Metadata\Tables\*.cs Runtime\Metadata\Runtime\*.cs Runtime\Vm\*.cs Runtime\Loader\*.cs Runtime\Loader\PE\*.cs Runtime\System\*.cs Runtime\System\IO\*.cs 
call gmcs -lib:Bin -target:library -unsafe -out:Bin\Mosa.Platforms.x86.dll -reference:System.dll -reference:Mosa.RunTime.dll Platforms\x86\*.cs Platforms\x86\Constraints\*.cs Platforms\x86\Instructions\*.cs Platforms\x86\Instructions\Intrinsics\*.cs 
call gmcs -lib:Bin -target:exe -unsafe -out:Bin\mosacl.exe -reference:Mosa.Kernel.dll -reference:Mosa.Platforms.x86.dll -reference:Mosa.Runtime.dll -reference:System.Core.dll -reference:System.Data.dll -reference:System.dll -reference:System.Xml.dll Tools\Compiler\*.cs Tools\Compiler\Boot\*.cs Tools\Compiler\Linkers\*.cs Tools\Compiler\LinkTimeCodeGeneration\*.cs Tools\Compiler\Symbols\Pdb\*.cs Tools\Compiler\TypeInitializers\*.cs 
call gmcs -lib:Bin -target:exe -out:Bin\MakeBootImage.exe -reference:Mosa.ClassLib.dll -reference:Mosa.DeviceSystem.dll -reference:Mosa.DeviceDrivers.dll -reference:Mosa.FileSystem.dll -reference:Mosa.EmulatedDevices.dll Tools\MakeBootImage\*.cs 
call gmcs -lib:Bin -target:exe -unsafe -out:Bin\Mosa.HelloWorld.exe HelloWorld\*.cs 
