// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Platform.ESP32.Instructions;

namespace Mosa.Platform.ESP32
{
	/// <summary>
	/// ESP32 Instructions
	/// </summary>
	public static class ESP32
	{
		public static readonly Add32 Add32 = new Add32();
		public static readonly Nop32 Nop32 = new Nop32();
	}
}
