// Copyright (c) MOSA Project. Licensed under the New BSD License.

// This code was generated by an automated template.

using Mosa.Compiler.Framework;

namespace Mosa.Compiler.ARM64;

/// <summary>
/// ARM64 Instruction Map
/// </summary>
public static class ARM64Instructions
{
	public static readonly List<BaseInstruction> List = new() {
		ARM64.Nop,
	};
}
