name: Tests

on:
  push:
  pull_request:

jobs:
  build-unix:
    name: Linux Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Update Package Respository
        run: sudo apt-get -y -o Acquire::Check-Valid-Until=false update
      - name: Install New Packages
        run: sudo apt-get install -y git wget qemu qemu-system qemu-system-x86
      - name: Restore nuget Packages
        run: dotnet restore Source/Mosa.LinuxCI.sln
      - name: Build
        run: msbuild /verbosity:minimal Source/Mosa.LinuxCI.sln
      - name: Testing Operating Systems
        run: bin/Mosa.Tool.Mosactl test
      - name: Unit Tests
        run: bin/Mosa.Tool.Mosactl unittest

  build-mswin:
    name: Windows Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Restore nuget packages
        run: dotnet restore Mosa.sln
        working-directory: Source
      - name: Build
        run: msbuild Source/Mosa.sln
      - name: Testing Operating Systems
        run: bin/Mosa.Tool.Mosactl test
      - name: Unit Tests
        run: bin/Mosa.Tool.Mosactl unittest
