namespace System.Runtime.Intrinsics.X86;

public enum FloatComparisonMode : byte
{
	OrderedEqualNonSignaling,
	OrderedLessThanSignaling,
	OrderedLessThanOrEqualSignaling,
	UnorderedNonSignaling,
	UnorderedNotEqualNonSignaling,
	UnorderedNotLessThanSignaling,
	UnorderedNotLessThanOrEqualSignaling,
	OrderedNonSignaling,
	UnorderedEqualNonSignaling,
	UnorderedNotGreaterThanOrEqualSignaling,
	UnorderedNotGreaterThanSignaling,
	OrderedFalseNonSignaling,
	OrderedNotEqualNonSignaling,
	OrderedGreaterThanOrEqualSignaling,
	OrderedGreaterThanSignaling,
	UnorderedTrueNonSignaling,
	OrderedEqualSignaling,
	OrderedLessThanNonSignaling,
	OrderedLessThanOrEqualNonSignaling,
	UnorderedSignaling,
	UnorderedNotEqualSignaling,
	UnorderedNotLessThanNonSignaling,
	UnorderedNotLessThanOrEqualNonSignaling,
	OrderedSignaling,
	UnorderedEqualSignaling,
	UnorderedNotGreaterThanOrEqualNonSignaling,
	UnorderedNotGreaterThanNonSignaling,
	OrderedFalseSignaling,
	OrderedNotEqualSignaling,
	OrderedGreaterThanOrEqualNonSignaling,
	OrderedGreaterThanNonSignaling,
	UnorderedTrueSignaling
}
